= Gas model and state objects
:source-highlighter: rouge

A number of gas models are encoded in D-language modules and are available via
a generic interface.

== GasModel

[source,python]
----
# Python
gmodel = GasModel(file_name)
----

[source,lua]
----
-- Lua
gmodel = GasModel:new{file_name}
----

`file_name`::
  _string_, no default +
  Specifies the name of the detailed gas model configuration file.
  This is a Lua format file, constructed as described in the
  http://cfcfd.mechmining.uq.edu.au/pdfs/gas-user-guide.pdf[Gas Models User Guide].

=== Properties

[source,python]
----
# Python
gmodel.id
----

The index to the underlying D-language gas model that is initialized during construction
of the Python GasModel object.


[source,python]
----
# Python
gmodel.n_species
----

[source,lua]
----
-- Lua
gmodel:nSpecies()
----

Is the number of chemical species in the gas model.


[source,python]
----
# Python
gmodel.species_names
----

[source,lua]
----
-- Lua
gmodel:speciesName(isp)
----

In Python we get the list of the chemical species names in the gas model
as a list of strings.
In Lua, we specify the index for each species and get its name.
The indices of the particular species may be useful for some of the method calls below.


[source,python]
----
# Python
gmodel.n_modes
----

[source,lua]
----
-- Lua
gmodel.nModes()
----

Is the number of internal energy modes (separate to the thermal internal energy)
in the gas model.


[source,python]
----
# Python
gmodel.mol_masses
----

[source,lua]
----
-- Lua
gmodel:molMasses()
----

Is a list of molecular masses in units of kg/m^3.


=== Methods

[source,python]
----
# Python
gmodel.update_thermo_from_pT(gstate)
----

[source,lua]
----
-- Lua
gmodel:updateThermoFromPT(gstate)
----

Given a GasState object, and assuming that its pressure,
temperature and mass fractions are set,
compute the other thermodynamic properties of the gas state.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.update_thermo_from_rhou(gstate)
----

[source,lua]
----
-- Lua
gmodel:updateThermoFromRHOU(gstate)
----

Given a GasState object, and assuming that its density,
internal energy and mass fractions are set,
compute the other thermodynamic properties of the gas state.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.update_thermo_from_rhoT(gstate)
----

[source,lua]
----
-- Lua
gmodel:updateThermoFromRHOT(gstate)
----

Given a GasState object, and assuming that its density,
temperature and mass fractions are set,
compute the other thermodynamic properties of the gas state.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.update_thermo_from_rhop(gstate)
----

[source,lua]
----
-- Lua
gmodel:updateThermoFromRHOP(gstate)
----

Given a GasState object, and assuming that its density,
pressure and mass fractions are set,
compute the other thermodynamic properties of the gas state.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.update_thermo_from_ps(gstate, s)
----

[source,lua]
----
-- Lua
gmodel:updateThermoFromPS(gstate, s)
----

Given a GasState object and a value of entropy,
and assuming that gas state pressure and mass fractions are set,
compute the other thermodynamic properties of the gas state.
The units of entropy, `s`, are J/kg.K.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.update_thermo_from_hs(gstate, h, s)
----

[source,lua]
----
-- Lua
gmodel:updateThermoFromHS(gstate, h, s)
----

Given a GasState object and values of enthalpy and entropy,
and assuming that gas state mass fractions are set,
compute the other thermodynamic properties of the gas state.
The units of enthalpy, `h`, are J/kg and the units of entropy, `s`, are J/kg.K.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.update_sound_speed(gstate)
----

[source,lua]
----
-- Lua
gmodel:updateSoundSpeed(gstate)
----

The underlying D-language gas model has the sound-speed calculation
separate to the other calculations for other thermodynamic properties.
This function reflects that separation, hovever, the other Python
methods mentioned above actually do update the sound-speed along with
the other thermodynamic properties of the gas state; the Lua methods do not.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.update_trans_coeffs(gstate)
----

[source,lua]
----
-- Lua
gmodel:updateTransCoeffs(gstate)
----

Update the transport coefficients of viscosity and thermal conductivity.
The Python function returns `None`.


[source,python]
----
# Python
gmodel.Cv(gstate)
----

[source,lua]
----
-- Lua
gmodel:Cv(gstate)
----

Returns the specific heat capacity for a constant volume process, J/kg.K.


[source,python]
----
# Python
gmodel.Cp(gstate)
----

[source,lua]
----
-- Lua
gmodel:Cp(gstate)
----

Returns the specific heat capacity for a constant pressure process, J/kg.K.


[source,python]
----
# Python
gmodel.dpdrho_const_T(gstate)
----

[source,lua]
----
-- Lua
gmodel:dpdrhoConstT(gstate)
----

Returns the derivative. Equivalent to `RT` for a thermally perfect gas.


[source,python]
----
# Python
gmodel.R(gstate)
----

[source,lua]
----
-- Lua
gmodel:R(gstate)
----

Returns the gas constant for the gas state. Units are J/kg.K.


[source,python]
----
# Python
gmodel.gamma(gstate)
----

[source,lua]
----
-- Lua
gmodel:gamma(gstate)
----

Returns the ratio of specific heats for the gas state. Nondimensional.


[source,python]
----
# Python
gmodel.Prandtl(gstate)
----

[source,lua]
----
-- Lua
gmodel:Prandtl(gstate)
----

Returns the ratio of momentum diffusivity to thermal diffusivity. Nondimensional.


[source,python]
----
# Python
gmodel.internal_energy(gstate)
----

[source,lua]
----
-- Lua
gmodel:intEnergy(gstate)
----

Returns the full internal energy of the gas state.
This is the sum of thermal internal energy and any other internal energy modes
of the gas model.
Units are J/kg.


[source,python]
----
# Python
gmodel.enthalpy(gstate)
----

[source,lua]
----
-- Lua
gmodel:enthalpy(gstate)
----

Returns the specific enthalpy of the gas state, in J/kg.


[source,python]
----
# Python
gmodel.entropy(gstate)
----

[source,lua]
----
-- Lua
gmodel:entropy(gstate)
----

Returns the specific entropy of the gas state, in J/kg.K.


[source,python]
----
# Python
gmodel.molecular_mass(gstate)
----

[source,lua]
----
-- Lua
gmodel:molMass(gstate)
----

Returns the molecular mass of the gas state, in kg/m^3.
This is most useful for chemically-reacting gases where the value will
change with mixture fractions of the species.


[source,python]
----
# Python
gmodel.enthalpy_isp(gstate, isp)
----

[source,lua]
----
-- Lua
gmodel:enthalpy(gstate, isp)
----

Returns the specific enthalpy for a particular chemical species,
at index `isp`, of the gas state.
Units are J/kg.


[source,python]
----
# Python
gmodel.entropy_isp(gstate, isp)
----

[source,lua]
----
-- Lua
gmodel:entropy(gstate, isp)
----

Returns the specific entropy for a particular chemical species,
at index `isp`, of the gas state.
Units are J/kg.K.


[source,python]
----
# Python
gmodel.gibbs_free_energy_isp(gstate, isp)
----

[source,lua]
----
-- Lua
gmodel:gibbsFreeEnergy(gstate, isp)
----

Returns the Gibbs Free Energy value for a particular chemical species,
at index `isp`, of the gas state.
Units are J/kg.


[source,python]
----
# Python
gmodel.massf2molef(massf)
----

[source,lua]
----
-- Lua
gmodel:massf2molef(gstate)
----

Given the mass fractions of a gas mixture,
returns the list of equivalent mole fractions.
In Python, the mass-fraction values may be supplied in a dictionary.
In Lua, the mass fractions are taken from the GasState object.


[source,python]
----
# Python
gmodel.molef2massf(molef)
----

[source,lua]
----
-- Lua
gmodel:molef2massf(molef, gstate)
----

Given the mole fractions of a gas mixture,
returns the list of equivalent mass fractions.
The mole-fraction values may be supplied in a dictionary.
In the Lua call, the table of mass fractions in the GasState object is also updated.


== GasState

Any number of GasState objects may be constructed in the context of a GasModel object.

[source,python]
----
# Python
gstate = GasState(gmodel)
----

[source,lua]
----
-- Lua
gstate = GasState:new{gmodel}
----

In Python, the GasState object retains a reference to the gas model used in its construction.
In Lua, the GasState object is a Lua table with named entries.



=== Properties

[source,python]
----
# Python
gstate.id
----

The index to the underlying D-language gas state that is initialized during
the construction of the Python GasState object.


[source,python]
----
# Python
gstate.rho
----

[source,lua]
----
-- Lua
gstate.rho
----

Gas density, in kg/m^3.
This property may be used in an expression or a new value may be assigned.


[source,python]
----
# Python
gstate.p
----

[source,lua]
----
-- Lua
gstate.p
----

Gas pressure, in Pa.
This property may be used in an expression or a new value may be assigned.


[source,python]
----
# Python
gstate.T
----

[source,lua]
----
-- Lua
gstate.T
----

Gas temperature, in K.
This property may be used in an expression or a new value may be assigned.


[source,python]
----
# Python
gstate.u
----

[source,lua]
----
-- Lua
gstate.u
----

Thermal internal energy, in J/kg.
This property may be used in an expression or a new value may be assigned.


[source,python]
----
# Python
gstate.a
----

[source,lua]
----
-- Lua
gstate.a
----

Sound speed, m/s.
This property is read-only.


[source,python]
----
# Python
gstate.k
----

[source,lua]
----
-- Lua
gstate.k
----

Thermal conductivity, in W/m.K.
This property is read-only.


[source,python]
----
# Python
gstate.mu
----

[source,lua]
----
-- Lua
gstate.mu
----

Dynamic viscosity, Pa.s.
This property is read-only.


[source,python]
----
# Python
gstate.massf
----

[source,lua]
----
-- Lua
gstate.massf
----

In Python, this a list of the mass fractions of the chemical species.
It may be assigned a list with all of the species mass fraction values in order.
It may also be assigned a dictionary, with named entries.
In the dictionary form, you need provide only the non-zero values.
In any case, the mass fractions should sum to `1.0`.

In Lua, it is a table with named entries.


[source,python]
----
# Python
gstate.massf_as_dict
----

Is a dictionary of named mass-fraction values.
It is a read-only property.  You may, however, assign to the `massf` property.


[source,python]
----
# Python
gstate.molef
----

Is a list of the mole fractions of the chemical species.
It may be assigned a list with all of the species mass fraction values in order.
It may also be assigned a dictionary, with named entries.
In the dictionary form, you need provide only the non-zero values.
In any case, the mole fractions should sum to `1.0`.

[source,python]
----
# Python
gstate.molef_as_dict
----

Is a dictionary of named mole-fraction values.
It is a read-only property.  You may, however, assign to the `molef` property.


[source,python]
----
# Python
gstate.conc
----

Is a list of the concentrations, in mole/m^3, of the chemical species.
It is a read-only property.


[source,python]
----
# Python
gstate.conc_as_dict
----

Is a dictionary of named concentration values.
It is a read-only property.


[source,python]
----
# Python
gstate.u_modes
----

[source,lua]
----
-- Lua
gstate.u_modes
----

Is a list of internal-energy values for a multi-temperature gas.
Units are J/kg.
When assigning a list, the full list must be supplied.


[source,python]
----
# Python
gstate.T_modes
----

[source,lua]
----
-- Lua
gstate.T_modes
----

Is a list of temperature values, in K, for a multi-temperature gas.
When assigning a list, the full list must be supplied.


[source,python]
----
# Python
gstate.k_modes
----

[source,lua]
----
-- Lua
gstate.k_modes
----

Is a list of thermal diffusivity coefficient values, in W/m.K, for a multi-temperature gas.
It is a read-only property.


[source,python]
----
# Python
gstate.ceaSavedData
----

[source,lua]
----
-- Lua
gstate.ceaSavedData
----

Is a dictionary of the data saved from the call out to the CEA2 program
that was made when updating the thermodynamic properties for the gas state
of the equilibrium mixture.
This property is specific to the CEAgas model.
If it exists, it contains the entries:

`"p"`:: static pressure, Pa
`"rho"`:: density, kg/m^3
`"u"`:: specific internal energy, J/kg
`"h"`:: specific enthalpy, J/kg
`"T"`:: temperature, K
`"a"`:: sound speed, m/s
`"Mmass"`:: average molecular mass of the equilibrium mixture, kg/mole
`"Rgas"`:: effective gas constant, J/kg/K
`"gamma"`:: effective ratio of specific heats
`"Cp"`:: effective specific heat, constant pressure, J/kg
`"s"`:: specific entropy, J/kg.K
`"mu"`:: effective viscosity coefficient, Pa.s
`"mass"`:: dictionary of mass-fraction values for the species in the equilibrium mixture.


=== Methods

[source,python]
----
# Python
gstate.copy_values(other_gstate)
----

Copy property values from the `other_gstate` object.
It is assumed that the GasModel is the same for east of the GasState objects.


[source,python]
----
# Python
gstate.update_thermo_from_pT()
----

Assuming that its pressure, temperature and mass fractions are set,
compute the other thermodynamic properties of the gas state.
Returns `None`.


[source,python]
----
# Python
gstate.update_thermo_from_rhou()
----

Assuming that its density, internal energy and mass fractions are set,
compute the other thermodynamic properties of the gas state.
Returns `None`.


[source,python]
----
# Python
gstate.update_thermo_from_rhoT()
----

Assuming that its density, temperature and mass fractions are set,
compute the other thermodynamic properties of the gas state.
Returns `None`.


[source,python]
----
# Python
gstate.update_thermo_from_rhop()
----

Assuming that its density, pressure and mass fractions are set,
compute the other thermodynamic properties of the gas state.
Returns `None`.


[source,python]
----
# Python
gstate.update_thermo_from_ps(s)
----

Given a value of entropy, and
assuming that gas state pressure and mass fractions are set,
compute the other thermodynamic properties of the gas state.
The units of entropy, `s`, are J/kg.K.
Returns `None`.


[source,python]
----
# Python
gstate.update_thermo_from_hs(h, s)
----

Given values of enthalpy and entropy,
and assuming that gas state mass fractions are set,
compute the other thermodynamic properties of the gas state.
The units of enthalpy, `h`, are J/kg and the units of entropy, `s`, are J/kg.K.
Returns `None`.


[source,python]
----
# Python
gstate.update_sound_speed()
----

The underlying D-language gas model has the sound-speed calculation
separate to the other calculations for other thermodynamic properties.
This function reflects that separation, hovever, the other Python
methods mentiond above actually do update the sound-speed along with
the other thermodynamic properties of the gas state.
Returns `None`.


[source,python]
----
# Python
gstate.update_trans_coeffs()
----

Update the transport coefficients of viscosity and thermal conductivity.
Returns `None`.


=== Other properties
These are for the Python library.
In Lua, you can access the same data via the `GasModel` methods.


[source,python]
----
# Python
gstate.Cv
----

Returns the specific heat capacity for a constant volume process, J/kg.K.


[source,python]
----
# Python
gstate.Cp
----

Returns the specific heat capacity for a constant pressure process, J/kg.K.


[source,python]
----
# Python
gstate.dpdrho_const_T
----

Returns the derivative. Equivalent to `RT` for a thermally perfect gas.


[source,python]
----
# Python
gstate.R
----

Returns the gas constant for the gas state. Units are J/kg.K.


[source,python]
----
# Python
gstate.gamma
----

Returns the ratio of specific heats for the gas state. Nondimensional.


[source,python]
----
# Python
gmodel.Prandtl(gstate)
----

Returns the ratio of momentum diffusivity to thermal diffusivity. Nondimensional.


[source,python]
----
# Python
gstate.internal_energy
----

Returns the full internal energy of the gas state.
This is the sum of thermal internal energy and any other internal energy modes
of the gas model.
Units are J/kg.


[source,python]
----
# Python
gstate.enthalpy
----

Returns the specific enthalpy of the gas state, in J/kg.


[source,python]
----
# Python
gstate.entropy
----

Returns the specific entropy of the gas state, in J/kg.K.


[source,python]
----
# Python
gstate.molecular_mass
----

Returns the molecular mass of the gas state, in kg/m^3.
This is most useful for chemically-reacting gases where the value will
change with mixture fractions of the species.


[source,python]
----
# Python
gstate.enthalpy_isp(isp)
----

Returns the specific enthalpy for a particular chemical species,
at index `isp`, of the gas state.
Units are J/kg.


[source,python]
----
# Python
gstate.entropy_isp(isp)
----

Returns the specific entropy for a particular chemical species,
at index `isp`, of the gas state.
Units are J/kg.K.


[source,python]
----
# Python
gstate.gibbs_free_energy_isp(isp)
----

Returns the Gibbs Free Energy value for a particular chemical species,
at index `isp`, of the gas state.
Units are J/kg.


