roberts-image: roberts-clustering.lua roberts-images.py
	lmr custom-script -j roberts-clustering.lua
	python roberts-images.py

geometric-c-image: geometric-clustering.lua geometric-c-images.py
	lmr custom-script -j geometric-clustering.lua
	python geometric-c-images.py
	
gaussian-image: gaussian-clustering.lua gaussian-images.py
	lmr custom-script -j gaussian-clustering.lua
	python gaussian-images.py

vinokur-image: vinokur-clustering.lua vinokur-images.py
	lmr custom-script -j vinokur-clustering.lua
	python vinokur-images.py

vin-geom-image: vin-geom-clustering.lua vin-geom-images.py
	lmr custom-script -j vin-geom-clustering.lua
	python vin-geom-images.py
