:bezier: B&eacute;zier

= Geometric elements

The basic geometric elements available are points (`Vector3`),
paths, surfaces and volumes.

== Points
In the Eilmer input, any point can be specified as a Lua table with `x`, `y` and
`z` components or as a `Vector3` object.
If you are declaring points with no further need to perform vector operations,
then the table format is preferred (to reduce the syntactic noise in your input scripts).
To demonstrate these alternatives, here are examples of two valid inputs for constructing a line from `(1,2)` to `(4,5)`:
----
ab = Line:new{p0={x=1.0, y=2.0}, p1={x=4.0, y=5.0}}
ab2 = Line:new{p0=Vector3:new{x=1.0, y=2.0}, p1=Vector3:new{x=4.0, y=5.0}}
----

When using a Lua table, any missing `x`, `y` or `z` components will default to
a value of `0.0`.

Obviously, the form with points as Lua tables is more compact.
Why then would one want to use the long-form Vector3 objects?
Well, these are useful when you need to do calculations involving vector arithmetic.
This vector arithmetic (as vector operations) has been built for you
in the Eilmer ecosystem.
Read on in the next section.

== Vector3
This class defines geometric vector objects with three Cartesian components:
`x`, `y` and `z`.
The `Vector3` constructor accepts these components in a table, or another
`Vector3` object.
----
p0 = Vector3:new{x=1.0, y=2.0, z=3.0}
p1 = Vector3:new{p0}
----

=== Vector3 expressions
A number of methods have been defined so that you can write arithmetic expressions
that involve `Vector3` objects.

Sample expressions available for `Vector3` objects include:
----
p2 = -p0           -- negative copy --> Vector3:new{x=-1.0, y=-2.0, z=-3.0}
p2 = p0 + p1       -- addition --> Vector3:new{x=2.0, y=4.0, z=6.0}
p2 = p0 - p1       -- subtraction --> Vector3:new{x=0.0, y=0.0, z=0.0}
p2 = p0 * 3.0      -- scaling --> Vector3:new{x=3.0, y=6.0, z=9.0}
p2 = 3.0 * p0      -- scaling --> Vector3:new{x=3.0, y=6.0, z=9.0}
p2 = p0 / 3.0      -- scaling --> Vector3:new{x=1./3, y=2./3, z=3./3}
p2:normalize()     -- scales to unit magnitude -->
                   --     Vector3:new{x=0.267261, y=0.534522, z=0.801783}
p3 = unit(p0)      -- new unit vector of p0 -->
                   --     Vector3:new{x=0.267261, y=0.534522, z=0.801783}
a = vabs(p3)       -- magnitude --> 1.0
p1 = Vector3:new{p0}
b = dot(p0, p1)    -- dot product --> 14.0
p3 = cross(p0, p1) -- cross product --> Vector3:new{x=0.0, y=0.0, z=0.0}
----

== Path elements

`Path` objects are typically used to define boundaries for surfaces.
A `Path` object can be called to evaluate a point at parameter `t`,
where the parametric range is `0.0` to `1.0`.

The constructors for `Path` objects include:

`Line:new{p0, p1}`::
  Defines a straight line from point `p0` (`t=0`) to point `p1` (`t=1`).

`Bezier:new{points}`::
  Defines a {bezier} curve from the sequence of `points`.

`NURBS:new{points, weights, knots, degree}`::
  Defines a NURBS from control `points` with `weights`, `knot` vector and `degree`.

`Arc:new{p0, p1, centre}`::
  Defines a circular arc from point `p0` to point `p0` about `centre`.

`Arc3:new{p0, pmid, p1}`::
  Defines a circular through three points starting at `p0` through `pmid` ending at `p1`.

`Polyline:new{segments}`::
  Builds a single path from a sequence of `Path` objects defined in `segments`.

`Spline:new{points}`::
  Builds a spline of Bezier segments through the sequence of `points`.

`Spline2:new{filename}`::
  Builds a spline from data file specifed in `filename` key with points listed line by line.

`LuaFnPath:new{luaFnFname}`::
  Builds a path based on a user-supplied function (as a function of `t`) specified
  in `luaFnName` key.

`ArcLengthParameterizedPath:new{underlying_path}`::
  Derives path from `underlying_path` that has a uniformly-distributed set of points
  with parameter `t`.





