[project]
name = "pitot3"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "pyyaml",
    "numpy",
    "gdtk",
    "scipy",
]

[project.scripts]
pitot3 = "pitot3.cli:main"
pitot3-condition-builder = "pitot3.condition_builder:main"

[tool.setuptools]
packages = ["pitot3"]
