-- Auto-generated by prep-gas on: 26-May-2016 06:34:28

model = 'IdealGas'
IdealGas = {
   speciesName = 'air',
   mMass = 0.02896000,
   gamma = 1.40000000,
   entropyRefValues = {
      s1 = 0.00000000e+00,
      T1 = 298.15000000,
      p1 = 1.01325000e+05,
   },
   sutherlandVisc = {
      mu_ref = 1.71600000e-05,
      T_ref = 273.00000000,
      S = 111.00000000,
   },
   sutherlandThermCond = {
      k_ref = 2.41000000e-02,
      T_ref = 273.00000000,
      S = 194.00000000,
   }
}
