= Geometry library for Python
Peter A. Jacobs; Ingo Jahn; Rowan J. Gollan
2020-08-22
:toc: right
:stylesheet: readthedocs.css
:sectnums:
:imagesdir: geom

:leveloffset: +1

The loadable library is accessible from Python and Ruby.
It provides access to geometry functions for the construction of paths and surfaces
compatible with those available in the Eilmer flow solver.

This is the reference manual for the Python flavour of the library
which sits in the `gdtk.geom` package.
For example, to construct a simple linear path element
from within your Python script and then evaluate the midpoint on that line,
you might try the following:

----
from gdtk.geom.vector3 import Vector3
from gdtk.geom.path import *

a = Vector3(0.0, 2.0)
b = Vector3(2.0, 0.0)
line_ab = Line(p0=a, p1=b)
print("line_ab=", line_ab)
c = line_ab(0.5)
----

If you have not yet read the
https://gdtk.uqcloud.net/pdfs/geometry-user-guide.pdf[Geometry Package User Guide],
this is a good time to do so.

= Installing the library

The geometry library for Python3 is part of a larger gas-dynamics toolkit and
general getting started notes can be found at
https://gdtk.uqcloud.net/docs/getting-started/prerequisites .
There, you will see how to get a copy of the source code,
and a list of what other software you will need to build and install the tool kit,
and a collection of environment variables that need to be set.

To install the library, move to the gas source directory and use the `make` utility.
----
cd dgd/src/gas
make install
----
Even though this part of the package is a pure Python library,
the rest of the loadable library, including gas models,
will be built and installed with this command.
So that the Python interpreter can find the installed library,
set your environment variables with something like:

    export DGD=$HOME/dgdinst
    export PYTHONPATH=${PYTHONPATH}:${DGD}/lib


include::geom/elements.adoc[]

include::geom/sgrid.adoc[]

:leveloffset: -1

