= L1d Reference Manual for Users, v4.0
Peter A. Jacobs; Rowan J. Gollan
2020-04-29
:toc: right
:stylesheet: readthedocs.css
:sectnums:

:leveloffset: +1

L1d is a flow simulation code for quasi-one-dimensional gas slugs
coupled to pistons.
It turns out to be good at modelling the dynamics of free-piston-driven
shock tunnels and expansion tubes.

The set up of a simulation involves writing a Python input script
that defines a tube of varying area that contains one or more
GasSlug objects and zero or more Piston objects.
These components are coupled at their ends and given initial states.
Over small time steps, the L1d program then updates the flow state
in each cell within the gas slugs
according to the constraints of mass, momentum and energy.
The details of the gas state at various locations can be used to give
a prediction of the performance of the physical machine.

The following sections provide brief details on many items that
might go into your input script.

= Example
When setting up a new simulation, first define the tube as a set
of (x,d) break-points and identify regions of head-loss and
regions where the wall-temperature varies from the nominal value.
Create the GasSlugs, Pistons, and Diaphragms that will make up the gas path.
Note that places where two GasSlugs join will need a GasInterface to be defined.
Once all of the components have been
created, assemble the gas path and then set any of the time-stepping
parameters for which you want values other than the default.

Here is an example input script for the Sod shock-tube problem.
----
# sod.py
config.title = 'Sods ideal shock tube, 2020-04-04'
my_gm = add_gas_model('ideal-air-gas-model.lua')

# Define the tube walls.
add_break_point(0.0, 0.01)
add_break_point(3.0, 0.01)

# Create the gas-path.
left_wall = VelocityEnd(x0=0.0, vel=0.0)
driver_gas = GasSlug(p=100.0e3, vel=0.0, T=348.4, gmodel_id=my_gm, ncells=200)
interface = GasInterface(x0=0.5)
driven_gas = GasSlug(p=10.0e3, vel=0.0, T=278.7, gmodel_id=my_gm, ncells=100)
right_wall = VelocityEnd(x0=1.0, vel=0.0)
assemble_gas_path(left_wall, driver_gas, interface, driven_gas, right_wall)

# Set some time-stepping parameters
config.dt_init = 1.0e-7
config.max_time = 0.6e-3
config.max_step = 5000
add_dt_plot(0.0, 10.0e-6, 5.0e-6)
add_history_loc(0.7)
----

This script should define the gas path
----
       |                        |                        |
       +------ driver_gas ------+------ driven_gas ------+
       |                        |                        |
   left_wall                interface               right_wall
----
and can be invoked with the command

  $ l1d4-prep --job=sod

Upon getting to the end of the user's script, this program should then write

. a complete simulation parameter file ./sod/config.json
. A tube-definition file ./sod/tube.data
. State files for pistons, diaphragms and gas slugs.

Note that Python is very picky about whitespace.  If you cut and paste the
example from above, make sure that the lines start in the first column and
that indentation is consistent with Python's syntax rules.

= Configuration options

There are a large number of configuration options
that can be set in the input script.
The options are set in the input script by adding
lines of the form:

 config.option = value

Here are all of the available configuration options and the default
values if left unset.
Note you do not have to set all of these values in the input script.

`title` ::
  _string_, default: `""` +
  Short title string for embedding in the parameter and solution files.

    * reacting: (bool) If set to True, Rowan's finite-rate chemistry will
      be active.  (Default is False)

    * dt_init: (float) The size of the time-step that will be used for the
      first few simulation steps.
      After a few steps, the cfl condition takes over the determination
      of a suitable time-step.

    * max_time: (float) The simulation will stop if it reaches this time.
      It is most usual to use this critereon to stop the simulation.

    * max_step: The simulation will be stopped if it reaches
      this number of steps.
      This is mostly used to catch the problem of the calculation taking
      a very long time (measured by one's patience), possibly because
      the time-step size has decreased to an extremely small value.

    * cfl: (float) Largest allowable CFL number.
      The time step is adjusted to ensure that this value is not exceeded
      in any particular cell.
      A typical value of 0.25 seems to work well for simulations with
      sudden events such as diaphragm bursting, while a value as high as
      0.5 should be considered only for well-behaved flows.

    * t_order: (int)
      1=Euler time-stepping. This is generally cheap and nasty.
      2=predictor-corrector time-stepping, nominally second order.
      This is the default setting.
      It is, however, twice as CPU intensive as Euler time-stepping.

    * x_order: (int)
      1=use cell averages without high-order reconstruction.
      Use this only if the second-order calculation is showing problems.
      2=use limited reconstruction (nominally second order).
      This is the default selection.

    * dt_plot_list: (list of tuples)
      Specifies the frequency of writing complete solutions
      (for later plotting, maybe) and also for the writing of data at
      history locations.
      It may be convenient to have different frequencies of writing such
      output at different stages of the simulation.
      For example, free-piston driven shock tunnels have a fairly long
      period during which the piston travels the length of the compression
      tube and then a relatively short period, following diaphragm rupture,
      when all the interesting things happen.
      It is good to have low-frequency output during most of the compression
      process and higher-frequency output starting just before diaphragm
      rupture.
      Arranging good values may require some trial and error.
      Add entries to this list via the add_dt_plot function.

    * hloc_list: (list of floats)
      List of x-coordinates for the history locations.
      Add entries via the function add_history_loc.

= Gas Models

`gas_file_names` ::
  _list of strings_, default: [] +
  file names for the detailed gas models.
  There may be one or more, but you have to specify one when you
  make each GasSlug.

  add_gas_model(fileName)


= Tube
There is a single tube object that contains the area, and loss specification.
The user's script does not create one of these objects directly
but should specify the tube details by calling the add_xxxx functions.

The following attributes are available:

    * n: (int) The number of small segments that will be used to describe
      the tube's area distribution internal to the simulation.
      To enable a fast lookup process for the area calculation,
      the area variation between equally-spaced x-positions is taken
      to be linear.
      The default value is 4000 and probably won't need to be changed
      except for geometries with rapidly changing cross-sections.

    * xd_list: List of break-point tuples defining the tube wall.
      Add elements to the list via the function add_break_point.

    * T_nominal: (float) The nominal wall temperature (in degrees K)
      in the absence of a patch of differing temperature.

    * T_patch_list: (list of tuples)
      Regions of the tube wall that have temperature different to the
      nominal value can be specified via the function add_T_patch.

    * loss_region_list: (list of tuples)
      List of head-loss regions, usually associated
      with sudden changes in tube cross-section and diaphragm stations.
      Add regions via the function add_loss_region.

Add a break-point tuple to the tube-diameter description.

The tube is described as a set of (x,d)-coordinate pairs that
define break points in the profile of the tube wall.
You need at least 2 break points to define the tube.
Linear variation of diameter between the break points is assumed.

  add_break_point(x, d)

    :param x: (float) x-coordinate, in metres, of the break point
    :param d: (float) diameter, in metres, of the tube wall at the break-point.
    :returns: Number of break points defined so far.

Add a head-loss region to the tube description.

There is a momentum-sink term much like the so-called minor-loss terms
in the fluid mechanics text books.
The effect of the loss is spread over a finite region so that the cells
are gradually affected as they pass through the region

  add_loss_region(xL, xR, K)

    xL: (float) Left-end location, in metres, of the loss region.
    xR: (float) Right-end location, in metres, of the loss region.
    K: (float) Head-loss coefficient.  A value of 0.25 seems to be good for a
        reasonably smooth contraction such as the T4 main diaphragm station.
    returns: Number of loss regions defined so far.

Add a temperature patch for a region where the wall temperature
is different from the nominal value.

  add_T_patch(xL, xR, T)

    :param xL: (float) Left-end location, in metres, of the loss region.
    :param xR: (float) Right-end location, in metres, of the loss region.
    :param T: (float) Wall temperature in degrees K.
    :returns: Number of temperature patches defined so far.


= Dynamic components

== GasSlug
Contains the gas properties and discretisation for each gas slug.

The user may create more than one gas slug to describe the initial
gas properties throughout the facility.

Note that a slug needs to have appropriate end-conditions.
This is achieved by creating end-condition objects such as
FreeEnd and VelocityEnd objects and then assembling
the gas-path via a call to the function assemble_gas_path.


  GasSlug(gmodel_id = None,
                 p = 100.0e3,
                 vel = 0.0,
                 T = 300.0,
                 T_modes = [],
                 massf = [1.0,],
                 label="",
                 ncells = 10,
                 to_end_L=False,
                 to_end_R=False,
                 cluster_strength=0.0,
                 viscous_effects=0, # several options were available in L1d3
                 adiabatic=False,
                 hcells=[],
                 )


        Most parameters have default properties so that only the user
        needs to override the ones that they wish to set differently.

        Note that the locations of the ends of the slug are communicated
        through end-condition objects that are attached during assembly
        of the gas path.

        :param gmodel_id: (int) index of the gas-model file name.
        :param p: (float) Pressure in Pa.
        :param vel: (float) Velocity in m/s.
        :param T: (float) Temperature in degrees K.
        :param T_modes: (list of float) Temperatures, in K, for the other energy modes.
        :param massf: Mass fractions supplied as a list of floats
            or a dictionary of species names and floats.
            The number of mass fraction values should match the number
            of species expected by the selected gas model.
        :param label: Optional (string) label for the gas slug.
        :param ncells: (int) Number of cells within the gas slug.
        :param to_end_L: (bool) Flag to indicate that cells should
            be clustered to the left end.
        :param to_end_R: (bool) Flag to indicate that cells should
            be clustered to the right end.
        :param cluster_strength: (float) As this value approaches 1.0 from above,
            the clustering gets stronger.
            A value of zero indicates no clustering.
        :param viscous_effects: (int) A nonzero value activates the viscous effects.
            0 = inviscid equations only;
            1 = include viscous source terms F_wall, loss, q,
            friction factor for pipe flow;
        :param adiabatic: (bool) Flag to indicate that there should
            be no heat transfer at the tube wall.
        :param hcells: Either the index (int) of a single cell or
            a list of indices of cells for which the data are
            to be written every dt_his seconds, as set by add_dt_plot.
            Note that cells are indexed from 0 to ncells-1.

= Piston

  Piston(self, mass, diam, xL0, xR0, vel0,
                 front_seal_f=0.0, front_seal_area=0.0,
                 back_seal_f=0.0, back_seal_area=0.0,
                 p_restrain=0.0, is_restrain=0,
                 with_brakes=0, brakes_on=0,
                 x_buffer=10.e6, hit_buffer = 0,
                 label="")

        :param mass: (float) Mass of piston in kg.
        :param diam: (float) Face diameter, metres.
        :param xL0: (float) Initial position of left-end, metres.
            The initial position of the piston centroid is set
            midway between xL0 and xR0 while piston length is the
            difference (xR0 - xL0).
        :param xR0: (float) Initial position of right-end, metres.
        :param vel0: (float) Initial velocity (of the centroid), m/s.
        :param front_seal_f: (float) friction coefficient.
            Typical value might be 0.2.
        :param front_seal_area: (float) Seal area over which the front-side
            pressure acts.
            This is the effective area over which the compressed gas pressed the
            front-side seal against the tube wall.
            Friction force is this area multiplied by downstream-pressure by
            friction coefficient.
        :param back_seal_f: (float) friction coefficient.
            A typical value might be 0.2.
        :param back_seal_area: (float) Seal area over which the back-side
            pressure acts.
            Friction force is this area multiplied by downstream-pressure by
            friction coefficient.  This is for gun tunnel pistons that have
            flexible skirts that are pressed onto the tube wall by the pushing gas.
        :param p_restrain: (float) Pressure at which restraint will release.
            Some machines, such as two-stage light-gas guns, will
            hold the projectile in place with some form of mechanical
            restraint until the pressure behind the piston reaches
            a critical value.  The piston is then allowed to slide.
        :param is_restrain: (int) Status flag for restraint.
            0=free-to-move, 1=restrained, 2=predefined trajectory read from external file
        :param with_brakes: (int) Flag to indicate the presence of brakes.
            0=no-brakes, 1=piston-does-have-brakes.
            Such brakes, as on the T4 shock tunnel, allow forward
            motion of the piston but prevent backward motion by
            locking the piston against the tube wall.
        :param brakes_on: (int) Flag to indicate the state of the brakes.
            0=off, 1=on.
        :param x_buffer: (float) Position of the stopping buffer in metres.
            This is the location of the piston centroid at which the piston
            would strike the buffer (or brake, in HEG terminology).
            Note that it is different to the location of the front of
            the piston at strike.
        :param hit_buffer: (int) Flag to indicate state of buffer interaction.
            A value of 0 indicates that the piston has not (yet) hit the
            buffer.
            A value of 1 indicates that it has.
            Details of the time and velocity of the strike are recorded in
            the event file.
        :param label: (string) A bit of text for corresponding line in the Lp file.

    * The left- and right-end positions of the piston are
      also used to locate the ends of adjoining GasSlugs.
    * The basic piston model has inertia but no friction.
      To make accurate simulations of a particular facility,
      it is usually important to have some account of
      the friction caused by gas-seals and guide-rings that
      may be present on the piston.

= End Conditions

== Diaphragm
Creates a diaphragm with specified properties.

Diaphragm(x0, p_burst, is_burst=0, dt_hold=0.0,
                 dxL=0.0, dxR=0.0, label="",
                 slugL=None, slugL_end='R',
                 slugR=None, slugR_end='L')

        The connections to GasSlugs are made later via the function
        assemble_gas_path.

        :param x0: (float) x-position in the tube, metres.
            This value is used to determine the end-points of the GasSlugs.
        :param p_burst: (float) Pressure, in Pa, at which rupture is triggered.
        :param is_burst: (int) Flag to indicate the state of diaphragm.
            A value of 0 indicates that the diaphragm is intact while
            a value of 1 indicates that the diaphragm is ruptured and the
            GasSlugs are interacting.
        :param dt_hold: (float) Time delay, in seconds, from rupture trigger
            to actual rupture.
        :param dxL: (float) The distance over which p is averaged on left of
            the diaphragm.  The pressure difference between the left-
            and right-sided of the diaphragm is used to trigger rupture.
            The default value of 0.0 will cause the pressure in the
            gas cell immediately adjacent to the diaphragm to be used.
        :param dxR: (float) The distance, in metres, over which p is averaged
            on right-side of the diaphragm.
        :param label: A (string) label that will appear in the parameter file
            for this diaphragm.

== GasInterface
Creates as interface between two gas slugs at specified location.

  GasInterface(x0,
                 slugL=None, slugL_end='R',
                 slugR=None, slugR_end='L')

        x0: (float) Initial position, in metres.

== FreeEnd
Creates a GasSlug end-condition with a specified location.

  FreeEnd(x0,
                 slugL=None, slugL_end='R',
                 slugR=None, slugR_end='L')

        x0: (float) Initial position, in metres.

== VelocityEnd
Creates a GasSlug end-condition with a specified location and velocity.

  VelocityEnd(x0, vel=0.0,
                 slugL=None, slugL_end='R',
                 slugR=None, slugR_end='L')


        x0: (float) Initial position, in metres.
        v: (float) Velocity, in m/s, of the end-point of the GasSlug.

== PistonFace
Creates a GasSlug end-condition at a piston face.

  PistonFace(slugL=None, slugL_end='R',
                 slugR=None, slugR_end='L',
                 pistonL=None, pistonL_face='R',
                 pistonR=None, pistonR_face='L')


= Assembling a gas path
Assemble a gas path by making the logical connections between adjacent components.
The components are assembled left-to-right, as they are supplied
to the following function.

  assemble_gas_path(*components):


    :param components: An arbitrary number of arguments representing
        individual components or lists of components.
        Each component may be a GasSlug, Piston, or any
        other gas-path object, however, it doesn't always make sense
        to connect arbitrary components.
        For example, connecting a GasSlug to a Piston is reasonable
        but connecting a Piston to a Diaphragm without an intervening
        GasSlug does not make sense in the context of this simulation
        program.

  connect_pair(cL, cR):
    """
    Make the logical connection between a pair of components.

    :param cL: is left object
    :param cR: is right object

    Usually called by assemble_gas_path.

= Command-line usage


:leveloffset: -1

