= Gas-dynamic library for Python
Peter A. Jacobs; Rowan J. Gollan
2020-05-18
:toc: right
:stylesheet: readthedocs.css
:sectnums:

:leveloffset: +1

The loadable library is accessible from Python and Ruby.
It provides access to functions for the thermochemical gas model
and, built on top of that, simple state-to-state and
stream-tube flow analysis functions.

This is the reference manual for the Python flavour of the library and,
because of the history of development, the library comes in the `eilmer` package.
For example, to use the to set up a gas model and do a normal shock calculation
from within your Python script, you might try the following:

----
from eilmer.gas import GasModel, GasState, GasFlow

gmodel = GasModel('cea-air5species-gas-model.lua')
state1 = GasState(gmodel)
state1.p = 80.0e3 # Pa
state1.T = 300.0 # K
state1.update_thermo_from_pT()
state1.update_sound_speed()
print("# Initial test gas:")
print("#   state1: %s" % state1)

print("# Normal shock, given shock speed")
vs = 2890.0
print("#   vs=%g" % vs)
state2 = GasState(gmodel)
flow = GasFlow(gmodel)
v2, vg = flow.normal_shock(state1, vs, state2)
print("#   v2=%g vg=%g" % (v2, vg))
print("#   state2: %s" % state2)
----

If you have not yet read the
http://cfcfd.mechmining.uq.edu.au/pdfs/gas-user-guide.pdf[Gas Models User Guide],
this is a good time to do so.

= Installing the library

The gas models library for Python3 is part of a larger gas-dynamics toolkit and
general getting started notes can be found at
http://cfcfd.mechmining.uq.edu.au/docs/getting-started
There, you will see how to get a copy of the source code,
and a list of what other software you will need to build and install the tool kit,
and a collection of environment variables that need to be set.

To install the library, move to the gas source directory and use the `make` utility.
----
cd dgd/src/gas
make install
----
Note that the loadable library needs to be built with the DMD64 compiler and that
you need the Foreign-Function-Interface extensions for your Python and Ruby interpreters.
On a LinuxMint system this package is `python-cffi`.

So that the Python interpreter can find the installed library,
set your environment variables with something like:

    export DGD=$HOME/dgdinst
    export PYTHONPATH=${PYTHONPATH}:${DGD}/lib
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${DGD}/lib


include::gas/gas-model.adoc[]
include::gas/kinetics.adoc[]
include::flow/gas-flow.adoc[]
include::flow/ideal-gas.adoc[]

:leveloffset: -1

