= Gas-dynamic library
Peter A. Jacobs; Rowan J. Gollan
2021-04-05
:toc: right
:stylesheet: readthedocs.css
:sectnums:
:source-highlighter: rouge

:leveloffset: +1

Eilmer's gas-dynamic library is accessible from your Lua scripts
and is also available as a loadable library for Python and Ruby.
It provides access to functions for the thermochemical gas model and,
built on top of that, a number of functions for simple state-to-state and
stream-tube flow analysis.
This is the reference manual for the Python and Lua flavours of the library.

Lets start with a small example to set up a gas model and do a normal shock calculation.
From within your Python script, you might try the following:

[source,python]
----
# Python
from eilmer.gas import GasModel, GasState, GasFlow

gmodel = GasModel('cea-air5species-gas-model.lua')
state1 = GasState(gmodel)
state1.p = 125.0e3 # Pa
state1.T = 300.0 # K
state1.update_thermo_from_pT()
state1.update_sound_speed()
print("# Initial test gas:")
print("#   state1: %s" % state1)

print("# Normal shock, given shock speed")
vs = 2414.0
print("#   vs=%g" % vs)
state2 = GasState(gmodel)
flow = GasFlow(gmodel)
v2, vg = flow.normal_shock(state1, vs, state2)
print("#   v2=%g vg=%g" % (v2, vg))
print("#   state2: %s" % state2)
----

The same functions are available to a Lua script given to the `gas-calc` program.

[source,lua]
----
-- Lua
gmodel = GasModel:new{'cea-air5species-gas-model.lua'}
state1 = GasState:new{gmodel}
state1.p = 125.0e3; state1.T = 300.0
gmodel:updateThermoFromPT(state1)
print("state1:"); printValues(state1)

print("normal shock, given shock speed")
Vs = 2414.0
state2, V2, Vg = gasflow.normal_shock(state1, Vs)
print("    V2=", V2, "Vg=", Vg)
print("    state2:"); printValues(state2)
----

Note that there are small but significant differences in calling the functions
from Lua, compared with Python3.
If you have not yet read the
https://gdtk.uqcloud.net/pdfs/gas-user-guide.pdf[Gas Models User Guide],
this is a good time to do so.

= Installing the library

The gas models library for is part of a larger gas-dynamics toolkit and
general getting started notes can be found at
https://gdtk.uqcloud.net/docs/getting-started/prerequisites .
There, you will see how to get a copy of the source code,
and a list of what other software you will need to build and install the tool kit,
and a collection of environment variables that need to be set.

To install the library and the gas-calc program,
move to the gas source directory and use the `make` utility.
----
cd dgd/src/gas
make install
----
Note that the loadable library needs to be built with the DMD64 compiler and that
you need the Foreign-Function-Interface extensions for your Python and Ruby interpreters.
On a LinuxMint system this package is `python-cffi`.

So that the Python interpreter can find the installed library,
set your environment variables with something like:

    export DGD=$HOME/dgdinst
    export PYTHONPATH=${PYTHONPATH}:${DGD}/lib
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${DGD}/lib


include::gas/gas-model.adoc[]
include::gas/kinetics.adoc[]
include::flow/gas-flow.adoc[]
include::flow/ideal-gas.adoc[]

:leveloffset: -1

