= Numerical methods library for Python
Peter A. Jacobs; Rowan J. Gollan
2020-08-22
:toc: right
:stylesheet: readthedocs.css
:sectnums:

:leveloffset: +1

This library provides access to various numerical methods that we have found useful
for the construction of our gas-dynamics tools.
Because of the history of development, the library comes in the `eilmer` package.

= Installing the library

This numerical-methods library for Python3 is part of a larger gas-dynamics toolkit and
general getting started notes can be found at
http://cfcfd.mechmining.uq.edu.au/docs/getting-started
There, you will see how to get a copy of the source code,
and a list of what other software you will need to build and install the tool kit,
and a collection of environment variables that need to be set.

To install the library, move to the gas source directory and use the `make` utility.
----
cd dgd/src/gas
make install
----
Even though this part of the package is a pure Python library,
the rest of the loadable library, including gas models,
will be built and installed with this command.
So that the Python interpreter can find the installed library,
set your environment variables with something like:

    export DGD=$HOME/dgdinst
    export PYTHONPATH=${PYTHONPATH}:${DGD}/lib


:leveloffset: -1

