db.aC3H5 = {}
db.aC3H5.atomicConstituents = {C=3,H=5,}
db.aC3H5.charge = 0
db.aC3H5.M = {
   value = 41.071800e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.aC3H5.gamma = {
   value = 1.1502e00,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.aC3H5.sigma = {
   value = 4.982,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'USC-Mech II transport file.'
}
db.aC3H5.epsilon = {
   value = 266.800,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'USC-Mech II transport file.'
}
db.aC3H5.grimechThermoCoeffs = {
   notes = 'data from USC-Mech II',
   nsegments = 2,
   T_break_points = {300.0, 1000.0, 3000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      0.13631835E+01,
      0.19813821E-01,
      0.12497060E-04,
     -0.33355555E-07,
      0.15846571E-10,
      0.19245629E+05,
      0.17173214E+02,
   },
   segment1 = {
      0,
      0,
      0.65007877E+01,
      0.14324731E-01,
     -0.56781632E-05,
      0.11080801E-08,
     -0.90363887E-13,
      0.17482449E+05,
     -0.11243050E+02,
   }
}
db.aC3H5.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
     -4.315996e+04,
      1.441601e+03,
     -1.197014e+01,
      7.319796e-02,
     -9.066358e-05,
      6.077059e-08,
     -1.658826e-11,
      1.232157e+04,
      8.563173e+01,
   },
   segment1 = {
      4.094571e+06,
     -1.676676e+04,
      3.123006e+01,
     -2.885450e-03,
      5.211344e-07,
     -5.058284e-11,
      2.039933e-15,
      1.185720e+05,
     -1.823070e+02
    }
}
db.aC3H5.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 3000.000,
      A = -2.737260561578e+01,
      B = 5.270213437016e+00,
      C = -5.843750571241e-01,
      D = 2.467473070508e-02,
   }
}
db.aC3H5.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 3000.000,
      A = -3.326474626507e+01,
      B = 9.549029292733e+00,
      C = -9.860839719784e-01,
      D = 3.644127580075e-02,
   }
}

