--Auto-Generated File
db.C2H = {}
db.C2H.atomicConstituents = {C=2,H=1,O=0,Ar=0,He=0,N=0}
db.C2H.charge = 0
db.C2H.M = {
    value = 0.025029,
    units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.C2H.gamma = {
   value = 1.246482,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.C2H.sigma = {
   value = 4.100,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = ' '
}
db.C2H.epsilon = {
   value = 209.000000,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = ' '
}
db.C2H.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      1.343669487e+04,
     -5.067970720e+02,
      7.772107410e+00,
     -6.512339820e-03,
      1.030117855e-05,
     -5.880147670e-09,
      1.226901861e-12,
      6.892269990e+04,
     -1.871881626e+01
   },
   segment1 = {
      3.922334570e+06,
     -1.204751703e+04,
      1.756172920e+01,
     -3.655442940e-03,
      6.987685430e-07,
     -6.825162010e-11,
      2.719262793e-15,
      1.433266627e+05,
     -9.561634380e+01
   }
}
db.C2H.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2, 
   T_break_points = {200.0, 1000.0, 3500.0},
   T_blend_ranges = {400.0},
   segment0 ={
      0.000000000000e+00,
      0.000000000000e+00,
      2.889657330000e+00,
      1.340996110000e-02,
     -2.847695010000e-05,
      2.947910450000e-08,
     -1.093315110000e-11,
      6.683939320000e+04,
      6.222964380000e+00,
   },
   segment1 = {
      0.000000000000e+00,
      0.000000000000e+00,
      3.167806520000e+00,
      4.752219020000e-03,
     -1.837870770000e-06,
      3.041902520000e-10,
     -1.772327700000e-14,
      6.712106500000e+04,
      6.635894750000e+00,
   }
}
db.C2H.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -2.532486828957e+01,
      B = 4.636835182216e+00,
      C = -5.132350959604e-01,
      D = 2.202694856015e-02,
   }
}
db.C2H.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -4.671028652157e+00,
      B = -1.552634627462e+00,
      C = 4.455792117341e-01,
      D = -2.549920860076e-02,
   }
}
db.C2H.Hf = {
   value = 566200.482,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
