db.C2H4 = {}
db.C2H4.atomicConstituents = {C=2,H=4,}
db.C2H4.charge = 0
db.C2H4.M = {
   value = 28.053160e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.C2H4.gamma = {
   value = 1.2393e+00,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.C2H4.sigma = {
   value = 3.971,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.C2H4.epsilon = {
   value = 280.800,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.C2H4.Lewis = {
   value = 1.402
}
db.C2H4.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 3500.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      3.95920148E+00,
     -7.57052247E-03,
      5.70990292E-05,
     -6.91588753E-08,
      2.69884373E-11,
      5.08977593E+03,
      4.09733096E+00,
   },
   segment1 = {
      0,
      0,
      2.03611116E+00,
      1.46454151E-02,
     -6.71077915E-06,
      1.47222923E-09,
     -1.25706061E-13,
      4.93988614E+03,
      1.03053693E+01,
   }
}
db.C2H4.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
     -1.163606e+05,
      2.554852e+03,
     -1.609746e+01,
      6.625779e-02,
     -7.885082e-05,
      5.125225e-08,
     -1.370340e-11,
     -6.176191e+03,
      1.093338e+02,
   },
   segment1 = {
      3.408764e+06,
     -1.374848e+04,
      2.365898e+01,
     -2.423804e-03,
      4.431396e-07,
     -4.352683e-11,
      1.775411e-15,
      8.820429e+04,
     -1.371278e+02
   }
}
db.C2H4.ceaViscosity = {
   notes = 'GORDON;NASATM86885,OCT1984',
   nsegments = 2,
   segment0 = {
      T_lower = 300.000,
      T_upper = 1000.000,
      A = 0.55243600E00,
      B = -0.16260917E03,
      C = 0.64734038E04,
      D = 0.19463233E01,
    },
   segment1 = {
      T_lower = 1000.000,
      T_upper = 5000.000,
      A = 0.65385054E00,
      B = 0.51157317E02,
      C = -0.54731184E05,
      D = 0.10933538E01,
    },
}
db.C2H4.ceaThermCond = {
   notes = 'GORDON;NASATM86885,OCT1984',
   nsegments = 2,
   segment0 = {
      T_lower = 300.000,
      T_upper = 1000.000,
      A = 0.77957663E00,
      B = -0.47857623E03,
      C = 0.32147858E05,
      D = 0.21827872E01,
    },
   segment1 = {
      T_lower = 1000.000,
      T_upper = 5000.000,
      A = 0.48277394E00,
      B = -0.91773465E03,
      C = 0.11528060E06,
      D = 0.45824405E01,
    },
}

db.C2H4.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -2.580836606635e+01,
      B = 4.671473377835e+00,
      C = -4.951477412808e-01,
      D = 2.031861716368e-02,
   }
}
db.C2H4.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -1.876932653720e+01,
      B = 3.279081810443e+00,
      C = -7.600615678041e-02,
      D = -7.052525306715e-03,
   }
}

db.C2H4.Hf = {
   value = 52500.0,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
