db.C2H5 = {}
db.C2H5.atomicConstituents = {C=2,H=5,}
db.C2H5.charge = 0
db.C2H5.M = {
   value = 29.061100e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.C2H5.gamma = {
   value = 1.1963e+00,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.C2H5.sigma = {
   value = 4.302,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.C2H5.epsilon = {
   value = 252.300,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.C2H5.Lewis = {
   value = 1.551
}
db.C2H5.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 3500.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      4.30646568E+00,
     -4.18658892E-03,
      4.97142807E-05,
     -5.99126606E-08,
      2.30509004E-11,
      1.28416265E+04,
      4.70720924E+00,
   },
   segment1 = {
      0,
      0,
      1.95465642E+00,
      1.73972722E-02,
     -7.98206668E-06,
      1.75217689E-09,
     -1.49641576E-13,
      1.28575200E+04,
      1.34624343E+01,
   }
}
db.C2H5.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
     -1.411313e+05,
      2.714285e+03,
     -1.534978e+01,
      6.451673e-02,
     -7.259144e-05,
      4.599116e-08,
     -1.218368e-11,
      5.981419e+02,
      1.090967e+02,
   },
   segment1 = {
      4.169220e+06,
     -1.662982e+04,
      2.795442e+01,
     -3.051716e-03,
      5.685160e-07,
     -5.682864e-11,
      2.355649e-15,
      1.137010e+05,
     -1.639358e+02
   }
}

db.C2H5.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -2.593014146501e+01,
      B = 4.747559219867e+00,
      C = -5.145597297061e-01,
      D = 2.154750839715e-02,
   }
}
db.C2H5.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -1.527203989367e+01,
      B = 1.873182769765e+00,
      C = 1.110291998328e-01,
      D = -1.533035825556e-02,
   }
}

db.C2H5.Hf = {
   value = 118658.24,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
