db.C3H6 = {}
db.C3H6.atomicConstituents = {C=3,H=6,}
db.C3H6.charge = 0
db.C3H6.M = {
   value = 42.079740e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.C3H6.gamma = {
   value = 1.1474e00,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.C3H6.sigma = {
   value = 4.982,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'USC-Mech II transport file.'
}
db.C3H6.epsilon = {
   value = 266.800,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'USC-Mech II transport file.'
}
db.C3H6.grimechThermoCoeffs = {
   notes = 'data from USC-Mech II',
   nsegments = 2,
   T_break_points = {300.0, 1000.0, 5000.0},
   T_blend_ranges = {400.0},
   segment0 ={
      0,
      0,
      0.01493307E+02,
      0.02092518E+00,
      0.04486794E-04,
     -0.01668912E-06,
      0.07158146E-10,
      0.01074826E+05,
      0.01614534E+03,
   },
   segment1 = {
      0,
      0,
      0.06732257E+02,
      0.01490834E+00,
     -0.04949899E-04,
      0.07212022E-08,
     -0.03766204E-12,
     -0.09235703E+04,
     -0.01331335E+03,
   }
}
db.C3H6.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
     -1.912462e+05,
      3.542074e+03,
     -2.114879e+01,
      8.901485e-02,
     -1.001429e-04,
      6.267959e-08,
     -1.637871e-11,
     -1.529962e+04,
      1.407641e+02,
   },
   segment1 = {
      5.017620e+06,
     -2.086084e+04,
      3.644156e+01,
     -3.881191e-03,
      7.278677e-07,
     -7.321204e-11,
      3.052176e-15,
      1.261245e+05,
     -2.195716e+02
   }
}
db.C3H6.ceaViscosity = {
   notes = 'GORDON;NASATM86885,OCT1984',
   nsegments = 2,
   segment0 = {
      T_lower = 300.000,
      T_upper = 1000.000,
      A = 0.52642893E00,
      B = -0.24304494E03,
      C = 0.14490001E05,
      D = 0.21036650E01,
    },
   segment1 = {
      T_lower = 1000.000,
      T_upper = 5000.000,
      A = 0.64243372E00,
      B = 0.83055174E01,
      C = -0.61290810E05,
      D = 0.11264132E01,
    },
}
db.C3H6.ceaThermCond = {
   notes = 'GORDON;NASATM86885,OCT1984',
   nsegments = 2,
   segment0 = {
      T_lower = 300.000,
      T_upper = 1000.000,
      A = 0.75434495E00,
      B = -0.56817108E03,
      C = 0.39706666E05,
      D = 0.23579094E01,
    },
   segment1 = {
      T_lower = 1000.000,
      T_upper = 5000.000,
      A = 0.46796950E00,
      B = -0.98032164E03,
      C = 0.12025017E06,
      D = 0.46607118E01,
    },
}

db.C3H6.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 5000.000,
      A = -2.622497446663e+01,
      B = 4.773760930715e+00,
      C = -5.124555504018e-01,
      D = 2.122189081184e-02,
   }
}
db.C3H6.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 5000.000,
      A = -3.193319260373e+01,
      B = 8.804340373459e+00,
      C = -8.583432800778e-01,
      D = 2.968532569582e-02,
   }
}

