db.CH2 = {}
db.CH2.atomicConstituents = {C=1,H=2,}
db.CH2.charge = 0
db.CH2.M = {
   value = 14.0265800e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'CEA2::thermo.inp'
}
db.CH2.gamma = {
   value = 1.311,
   units = 'non-dimensional',
   description = 'ratio of specific heats at room temperature (= Cp/(Cp - R))',
   reference = 'using Cp evaluated from CEA2 coefficients at T=300.0 K'
}
db.CH2.sigma = {
   value = 3.800,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.CH2.epsilon = {
   value = 144.000,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.CH2.Lewis = {
   value = 1.023
}
db.CH2.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 3500.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      3.76267867E+00,
      9.68872143E-04,
      2.79489841E-06,
     -3.85091153E-09,
      1.68741719E-12,
      4.60040401E+04,
      1.56253185E+00,
   },
   segment1 = {
      0,
      0,
      2.87410113E+00,
      3.65639292E-03,
     -1.40894597E-06,
      2.60179549E-10,
     -1.87727567E-14,
      4.62636040E+04,
      6.17119324E+00,
   }
}
db.CH2.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      3.218922e+04,
     -2.877602e+02,
      4.203584e+00,
      3.455406e-03,
     -6.746193e-06,
      7.654572e-09,
     -2.870328e-12,
      4.733625e+04,
     -2.143629e+00,
   },
   segment1 = {
      2.550418e+06,
     -7.971625e+03,
      1.228924e+01,
     -1.699123e-03,
      2.991729e-07,
     -2.767007e-11,
      1.051342e-15,
      9.642217e+04,
     -6.094740e+01
   }
}

db.CH2.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -2.274340688184e+01,
      B = 3.690876678686e+00,
      C = -4.016022859623e-01,
      D = 1.764923161171e-02,
   }
}
db.CH2.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -2.125379834838e+00,
      B = -2.235463527624e+00,
      C = 5.038887351549e-01,
      D = -2.646402375981e-02,
   }
}

db.CH2.Hf = {
   value = 390364.517,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
