db.CH3O = {}
db.CH3O.atomicConstituents = {C=1,H=3,O=1,}
db.CH3O.charge = 0
db.CH3O.M = {
   value = 31.033920e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.CH3O.gamma = {
   value = 1.2802e+00,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.CH3O.sigma = {
   value = 3.690,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.CH3O.epsilon = {
   value = 417.000,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.CH3O.Lewis = {
   value = 1.360
}
db.CH3O.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2,
   T_break_points = {300.0, 1000.0, 3000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      0.02106204E+02,
      0.07216595E-01,
      0.05338472E-04,
     -0.07377636E-07,
      0.02075610E-10,
      0.09786011E+04,
      0.13152177E+02,
   },
   segment1 = {
      0,
      0,
      0.03770799E+02,
      0.07871497E-01,
     -0.02656384E-04,
      0.03944431E-08,
     -0.02112616E-12,
      0.12783252E+03,
      0.02929575E+02,
   }
}
db.CH3O.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      8.657118e+04,
     -6.631685e+02,
      2.257456e+00,
      2.266284e-02,
     -2.970566e-05,
      2.199341e-08,
     -6.588043e-12,
      4.174102e+03,
      8.174778e+00,
   },
   segment1 = {
      2.101188e+06,
     -8.841969e+03,
      1.822646e+01,
     -1.743485e-03,
      3.340434e-07,
     -3.430673e-11,
      1.473898e-15,
      5.309582e+04,
     -9.422501e+01
   }
}

db.CH3O.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 3000.000,
      A = -2.596824781753e+01,
      B = 4.466550601397e+00,
      C = -4.304908052551e-01,
      D = 1.601059649628e-02,
   }
}
db.CH3O.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 3000.000,
      A = -2.187848840881e+01,
      B = 4.318601152219e+00,
      C = -1.996927776238e-01,
      D = -2.088356518496e-03,
   }
}

db.CH3O.Hf = {
   value = 13000.0,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
