db.H2CC = {}
db.H2CC.atomicConstituents = {H=2,C=2,}
db.H2CC.charge = 0
db.H2CC.M = {
   value = 26.0372800e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'CEA2::thermo.inp'
}
db.H2CC.gamma = {
   value = 1.242,
   units = 'non-dimensional',
   description = 'ratio of specific heats at room temperature (= Cp/(Cp - R))',
   reference = 'using Cp evaluated from CEA2 coefficients at T=300.0 K'
}
db.H2CC.sigma = {
   value = 4.100,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'USC-Mech II transport file'
}
db.H2CC.epsilon = {
   value = 209.000,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'USC-Mech II transport file'
}
db.H2CC.grimechThermoCoeffs = {
   notes = 'data from USC-Mech II',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      0.32815483E+01,
      0.69764791E-02,
     -0.23855244E-05,
     -0.12104432E-08,
      0.98189545E-12,
      0.48621794E+05,
      0.59203910E+01,
   },
   segment1 = {
      0,
      0,
      0.42780340E+01,
      0.47562804E-02,
     -0.16301009E-05,
      0.25462806E-09,
     -0.14886379E-13,
      0.48316688E+05,
      0.64023701E+00,
   }
}
db.H2CC.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
         -1.466042e+04,
      2.789476e+02,
      1.276230e+00,
      1.395015e-02,
     -1.475703e-05,
      9.476298e-09,
     -2.567602e-12,
      4.736110e+04,
      1.658226e+01,
   },
   segment1 = {
      1.940839e+06,
     -6.892718e+03,
      1.339582e+01,
     -9.368969e-04,
      1.470804e-07,
     -1.220040e-11,
      4.122392e-16,
      9.107113e+04,
     -6.337503e+01
    }
}

db.H2CC.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 6000.000,
      A = -2.396866153965e+01,
      B = 4.040169611213e+00,
      C = -4.252689499838e-01,
      D = 1.774234492713e-02,
   }
}
db.H2CC.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 6000.000,
      A = -1.534295035569e+01,
      B = 2.865727279816e+00,
      C = -1.600083918257e-01,
      D = 2.376301694764e-03,
   }
}

