db.HCCO = {}
db.HCCO.atomicConstituents = {C=2,H=1,O=1,}
db.HCCO.charge = 0
db.HCCO.M = {
   value = 41.028740e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.HCCO.gamma = {
   value = 1.2067e00,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.HCCO.sigma = {
   value = 2.500,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.HCCO.epsilon = {
   value = 150.000,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.HCCO.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2,
   T_break_points = {300.0, 1000.0, 4000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      0.22517214E+01,
      0.17655021E-01,
     -0.23729101E-04,
      0.17275759E-07,
     -0.50664811E-11,
      0.20059449E+05,
      0.12490417E+02,
   },
   segment1 = {
      0,
      0,
      0.56282058E+01,
      0.40853401E-02,
     -0.15934547E-05,
      0.28626052E-09,
     -0.19407832E-13,
      0.19327215E+05,
     -0.39302595E+01,
   }
}
db.HCCO.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      6.959613e+04,
     -1.164594e+03,
      9.456616e+00,
     -2.331241e-03,
      5.161874e-06,
     -3.526170e-09,
      8.599143e-13,
      2.535004e+04,
     -2.726355e+01,
   },
   segment1 = {
      1.093922e+06,
     -4.498228e+03,
      1.246446e+01,
     -6.343317e-04,
      1.108549e-07,
     -1.125489e-11,
      5.689152e-16,
      4.652280e+04,
     -5.099070e+01
    }
}

db.HCCO.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 4000.000,
      A = -2.047911174161e+01,
      B = 3.289579534067e+00,
      C = -3.425514016760e-01,
      D = 1.478685784020e-02,
   }
}
db.HCCO.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 4000.000,
      A = -1.709974427710e+01,
      B = 4.224884718432e+00,
      C = -3.726422242450e-01,
      D = 1.275222078039e-02,
   }
}

db.HCCO.Hf = {
   value = 176568.1,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
