db.HCO = {}
db.HCO.atomicConstituents = {C=1,H=1,O=1,}
db.HCO.charge = 0
db.HCO.M = {
   value = 29.018040e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'CEA2::thermo.inp',
}
db.HCO.gamma = {
   value = 1.316,
   units = 'non-dimensional',
   description = 'ratio of specific heats at room temperature (= Cp/(Cp - R))',
   reference = "Gokel (2004), Dean's Handbook of Organic Chemistry",
}
db.HCO.sigma = {
   value = 3.590,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.HCO.epsilon = {
   value = 498.000,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.HCO.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 3500.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      4.22118584E+00,
     -3.24392532E-03,
      1.37799446E-05,
     -1.33144093E-08,
      4.33768865E-12,
      3.83956496E+03,
      3.39437243E+00,
   },
   segment1 = {
      0,
      0,
      2.77217438E+00,
      4.95695526E-03,
     -2.48445613E-06,
      5.89161778E-10,
     -5.33508711E-14,
      4.01191815E+03,
      9.79834492E+00,
   }
}
db.HCO.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
     -1.189852e+04,
      2.151536e+02,
      2.730224e+00,
      1.806516e-03,
      4.984301e-06,
     -5.814568e-09,
      1.869690e-12,
      2.905756e+03,
      1.136773e+01,
   },
   segment1 = {
      6.949606e+05,
     -3.656223e+03,
      9.604731e+00,
     -1.117129e-03,
      2.875328e-07,
     -3.626248e-11,
      1.808330e-15,
      2.543704e+04,
     -3.582474e+01
    }
}

db.HCO.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -1.946125270029e+01,
      B = 1.583449384081e+00,
      C = -1.418736403518e-02,
      D = -3.703072867374e-03,
   }
}
db.HCO.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -2.790317887628e+00,
      B = -3.149564742925e+00,
      C = 7.513430765797e-01,
      D = -4.266290638275e-02,
   }
}

db.HCO.Hf = {
   value = 42397.85,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
