db.nC3H7 = {}
db.nC3H7.atomicConstituents = {C=3,H=7,}
db.nC3H7.charge = 0
db.nC3H7.M = {
   value = 43.087680e-3,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'Periodic table'
}
db.nC3H7.gamma = {
   value = 1.1314e00,
   units = 'non-dimensional',
   description = 'ratio of specific heats at 300.0K',
   reference = 'evaluated using Cp/R from Chemkin-II coefficients'
}
db.nC3H7.sigma = {
   value = 4.982,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'USC-Mech II transport file.'
}
db.nC3H7.epsilon = {
   value = 266.800,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'USC-Mech II transport file.'
}
db.nC3H7.grimechThermoCoeffs = {
   notes = 'data from USC-Mech II',
   nsegments = 2,
   T_break_points = {300.0, 1000.0, 3000.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      0.10491173E+01,
      0.26008973E-01,
      0.23542516E-05,
     -0.19595132E-07,
      0.93720207E-11,
      0.10312346E+05,
      0.21136034E+02,
   },
   segment1 = {
      0,
      0,
      0.77097479E+01,
      0.16031485E-01,
     -0.52720238E-05,
      0.75888352E-09,
     -0.38862719E-13,
      0.79762236E+04,
     -0.15515297E+02,
   }
}
db.nC3H7.ceaThermoCoeffs = {
   notes = 'NASA/TP—2002-211556',
   nsegments = 2,
   T_break_points = {200.0, 1000.0, 6000.0},
   T_blend_ranges = {400.0},
   segment0 = {
     -1.895337e+05,
      3.949517e+03,
     -2.606216e+01,
      1.121920e-01,
     -1.365292e-04,
      9.023663e-08,
     -2.441057e-11,
     -7.227877e+03,
      1.673706e+02,
   },
   segment1 = {
      5.646513e+06,
     -2.291087e+04,
      3.987275e+01,
     -4.106233e-03,
      7.562558e-07,
     -7.478263e-11,
      3.068984e-15,
      1.483007e+05,
     -2.403781e+02
   }
}

db.nC3H7.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 3000.000,
      A = -2.734864796957e+01,
      B = 5.270213096852e+00,
      C = -5.843750081534e-01,
      D = 2.467472836750e-02,
   }
}
db.nC3H7.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 300.000,
      T_upper = 3000.000,
      A = -3.138426993014e+01,
      B = 8.645992725716e+00,
      C = -8.407403308989e-01,
      D = 2.905510973744e-02,
   }
}

