db.O = {}
db.O.type = "atom"
db.O.atomicConstituents = {O=1,}
db.O.charge = 0
db.O.M = {
   value = 0.01599940,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'CEA2::thermo.inp'
}
db.O.gamma = {
   value = 1.66666667,
   units = 'non-dimensional',
   description = '(ideal) ratio of specific heats at room temperature',
   reference = 'monatomic gas'
}
db.O.sigma = {
   value = 2.750,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.O.epsilon = {
   value = 80.000,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.O.Lewis = {
   value = 0.712
}
db.O.electronic_levels = {
  Te = {
    value = {0.0, 15867.86, 33792.58, 73768.2, 76794.98, 86629.09},
    units = 'cm^(-1)',
    description = 'Electronic energy levels',
    reference = 'NIST'
  },
  g = {
    value = {9, 5, 1, 5, 3, 15},
    units = 'cm^(-1)',
    description = 'Degeneracy of electronic energy levels',
    reference = 'NIST'
  }
}
db.O.ceaThermoCoeffs = {
   nsegments = 4,
   T_break_points = {200.0, 1000.0, 6000.0, 20000.0, 50000.0},
   T_blend_ranges = {400.0, 1000.0, 1000.0},
   segment0 = {
      0.00000000e+00,
      0.00000000e+00,
      2.50000000e+00,
      0.00000000e+00,
      0.00000000e+00,
      0.00000000e+00,
      0.00000000e+00,
      2.92727578e+04,
      5.20440739e+00
   },
   segment1 = {
     -4.59493000e+05,
      1.36004299e+03,
      9.30779889e-01,
      9.08157296e-04,
     -2.81746654e-07,
      4.49451675e-11,
     -2.68564490e-15,
      2.06167786e+04,
      1.63928984e+01
   },
   segment2 = {
     -1.36180488e+09,
      9.17683684e+05,
     -2.46884942e+02,
      3.48520165e-02,
     -2.61713430e-06,
      9.91544159e-11,
     -1.44192000e-15,
     -7.15328977e+06,
      2.14015002e+03
   },
   segment3 = {
      4.38121309e+11,
     -8.98310623e+07,
      7.33626546e+03,
     -3.05369185e-01,
      6.90318054e-06,
     -8.09257822e-11,
      3.86322459e-16,
      8.10576891e+08,
     -7.16401144e+04
   },
   reference = "Johnston et al. AIAA Paper 2015-3110"
}
db.O.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2, 
   T_break_points = {200.0, 1000.0, 3500.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      3.16826710E+00,
     -3.27931884E-03,
      6.64306396E-06,
     -6.12806624E-09,
      2.11265971E-12,
      2.91222592E+04,
      2.05193346E+00,
   },
   segment1 = {
      0,
      0,
      2.56942078E+00,
     -8.59741137E-05,
      4.19484589E-08,
     -1.00177799E-11,
      1.22833691E-15,
      2.92175791E+04,
      4.78433864E+00,
   }
}
db.O.ceaViscosity = {
   nsegments = 2,
   segment0 = {
      T_lower = 1000.0,
      T_upper = 5000.0,
      A =  7.7269241e-01,
      B =  8.3842977e+01,
      C = -5.8502098e+04,
      D =  8.5100827e-01
   },
   segment1 = {
      T_lower = 5000.0,
      T_upper = 15000.0,
      A =  8.7669586e-01,
      B =  1.0158420e+03,
      C = -1.0884566e+06,
      D = -1.8001077e-01
   },
}
db.O.ceaThermCond = {
   nsegments = 2,
   segment0 = {
      T_lower = 1000.0,
      T_upper = 5000.0,
      A =  7.7271664e-01,
      B =  8.3989100e+01,
      C = -5.8580966e+04,
      D =  1.5179900e+00
   },
   segment1 = {
      T_lower = 5000.0,
      T_upper = 15000.0,
      A =  8.7676666e-01,
      B =  1.0170744e+03,
      C = -1.0906690e+06,
      D =  4.8644232e-01
   },
}

db.O.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -1.785314441989e+01,
      B = 2.112206043926e+00,
      C = -1.984976530122e-01,
      D = 8.935786220530e-03,
   }
}
db.O.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -1.027818773205e+01,
      B = 2.112205758221e+00,
      C = -1.984976113175e-01,
      D = 8.935784208992e-03,
   }
}

db.O.Hf = {
   value = 249175.003,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
