db.O2 = {}
db.O2.type = "molecule"
db.O2.molecule_type = "linear"
db.O2.theta_v = {
   value = 2273.53,
   units = 'K',
   description = 'characteristic vibrational temperature',
   reference = 'Capitelli et al (2005), Table 25. omega_e in ground state converted to K'
}
db.O2.theta_D = {
   value = 59417.0,
   units = 'K',
   description = 'dissociation temperature'
}
db.O2.electronic_levels = {
  g = {
    value = {3, 2, 1, 1, 6, 3},
    units = 'NA',
    description = 'degeneracy of electronic levels',
    reference = 'NIST'
  },
  Te = {
    value = {0.0, 7918.04, 13195.10, 33057.3, 34690.3, 35396.6},
    units = 'cm^(-1)',
    description = 'electronic excitation energy',
    reference = 'NIST'
  }
}
db.O2.atomicConstituents = {O=2,}
db.O2.charge = 0
db.O2.M = {
   value = 0.03199880,
   units = 'kg/mol',
   description = 'molecular mass',
   reference = 'from CEA2::thermo.inp'
}
db.O2.gamma = {
   value = 1.40000000,
   units = 'non-dimensional',
   description = '(ideal) ratio of specific heats at room temperature',
   reference = 'diatomic molecule at low temperatures, gamma = 7/5'
}
db.O2.sigma = {
   value = 3.458,
   units = 'Angstrom',
   description = 'Lennard-Jones potential distance',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.O2.epsilon = {
   value = 107.400,
   units = 'K',
   description = 'Lennard-Jones potential well depth.',
   reference = 'GRI-Mech 3.0 transport file.'
}
db.O2.SSH_mass_factor = {
   value = 1.0,
   units = "unitless",
   description = 'Mass factor = ( M ( Ma^2 + Mb^2 ) / ( 2 Ma Mb ( Ma + Mb ) )',
   reference = 'Thivet et al (1991) Phys. Fluids A 3 (11)'
}
db.O2.r_eq = {
   value = 1.21e-10,
   units = 'm',
   description = "Equilibrium intermolecular distance",
   reference = "Hirschfelder, Curtiss, Bird"
}
db.O2.Lewis = {
   value = 1.086
}
db.O2.ceaThermoCoeffs = {
   nsegments = 3,
   T_break_points = {200.0, 1000.0, 6000.0, 20000.0},
   T_blend_ranges = {400.0, 1000.0},
   segment0 = {
     -3.425563420e+04,
      4.847000970e+02,
      1.119010961e+00,
      4.293889240e-03,
     -6.836300520e-07,
     -2.023372700e-09,
      1.039040018e-12,
     -3.391454870e+03,
      1.849699470e+01,
   },
   segment1 = {
     -1.037939022e+06,
      2.344830282e+03,
      1.819732036e+00,
      1.267847582e-03,
     -2.188067988e-07,
      2.053719572e-11,
     -8.193467050e-16,
     -1.689010929e+04,
      1.738716506e+01,
   },
   segment2 = {
      4.975294300e+08,
     -2.866106874e+05,
      6.690352250e+01,
     -6.169959020e-03,
      3.016396027e-07,
     -7.421416600e-12,
      7.278175770e-17,
      2.293554027e+06,
     -5.530621610e+02,
   },
}
db.O2.grimechThermoCoeffs = {
   notes = 'data from GRIMECH 3.0',
   nsegments = 2, 
   T_break_points = {200.0, 1000.0, 3500.0},
   T_blend_ranges = {400.0},
   segment0 = {
      0,
      0,
      3.78245636E+00,
     -2.99673416E-03,
      9.84730201E-06,
     -9.68129509E-09,
      3.24372837E-12,
     -1.06394356E+03,
      3.65767573E+00,
   },
   segment1 = {
      0,
      0,
      3.28253784E+00,
      1.48308754E-03,
     -7.57966669E-07,
      2.09470555E-10,
     -2.16717794E-14,
     -1.08845772E+03,
      5.45323129E+00,
   }
}
db.O2.ceaViscosity = {
   nsegments = 3,
   segment0 = {
      T_lower = 200.0,
      T_upper = 1000.0,
      A =  6.0916180e-01,
      B = -5.2244847e+01,
      C = -5.9974009e+02,
      D =  2.0410801e+00
   },
   segment1 = {
      T_lower = 1000.0,
      T_upper = 5000.0,
      A =  7.2216486e-01,
      B =  1.7550839e+02,
      C = -5.7974816e+04,
      D =  1.0901044e+00
   },
   segment2 = {
      T_lower = 5000.0,
      T_upper = 15000.0,
      A =  7.3981127e-01,
      B =  3.9194906e+02,
      C = -3.7833168e+05,
      D =  9.0931780e-01
   },
}
db.O2.ceaThermCond = {
   nsegments = 3,
   segment0 = {
      T_lower = 200.0,
      T_upper = 1000.0,
      A =  7.7229167e-01,
      B =  6.8463210e+00,
      C = -5.8933377e+03,
      D =  1.2210365e+00
   },
   segment1 = {
      T_lower = 1000.0,
      T_upper = 5000.0,
      A =  9.0917351e-01,
      B =  2.9124182e+02,
      C = -7.9650171e+04,
      D =  6.4851631e-02
   },
   segment2 = {
      T_lower = 5000.0,
      T_upper = 15000.0,
      A = -1.1218262e+00,
      B = -1.9286378e+04,
      C =  2.3295011e+07,
      D =  2.0342043e+01
   },
}

db.O2.chemkinViscosity = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -2.000056657134e+01,
      B = 2.898260367046e+00,
      C = -3.018511062902e-01,
      D = 1.346540184145e-02,
   }
}
db.O2.chemkinThermCond = {
   notes = 'Generated by species-generator.py',
   nsegments = 1, 
   segment0 ={
      T_lower = 200.000,
      T_upper = 3500.000,
      A = -1.172264668036e+01,
      B = 2.184456084794e+00,
      C = -1.756136715791e-01,
      D = 7.271800113398e-03,
   }
}

db.O2.Hf = {
   value = 0.0,
   units = 'J/mol',
   description = 'Molar Heat of Formation at 298.15K',
   reference = 'CEA2::thermo.inp'
}
