= Boundary Conditions

To complete a definition of a FluidBlock, boundary conditions for all
block boundaries, need to be specified.
These may be given as a list to the FluidBock constructor or
they may be attached to particular boundaries of an already existing
FluidBlock object.
In the absence of your specification, the default boundary condition
is a slip wall, `WallBC_WithSlip`.


== Walls

=== Slip wall

  WallBC_WithSlip:new{label, group, is_design_surface, num_cntrl_pts}
  or
  WallBC_WithSlip0:new{label, group, is_design_surface, num_cntrl_pts}

is used where we want a solid wall with no viscous effects.
The effect of the solid wall is achieved with the use of ghost cells and
an appropriate reflection of the velocity vector.
This is the default boundary condition where no other condition is specified.

`label`::
  _string_, default "" +
  A tag string that may be applied to the boundary.

`group`::
  _string_, default "" +
  A tag or label for the group, to which this boundary belongs.
  It can be used to group the postprocessing of the data for several boundaries together.
  This might be for force and moment estimation, for example.

`is_design_surface`::
  _boolean_, default: `false` +
  Flag to indicate that this surface is one of Kyle's design surfaces.

`num_cntrl_pts`::
  _int_, default: `0`

There are variants to the basic wall condition.

  WallBC_WithSlip1:new{label, group, is_design_surface, num_cntrl_pts}

achieves a similar effect to WallBC_WithSlip0 but without the use of ghost cell data.
To do this, the code makes use of one-sided flux-calculators at the boundary.
You will need to specify this variant of the boundary condition for a moving-grid
simulation where this boundary wall may have non-zero velocity.
The one-sided flux calculators will correctly handle the normal component of the
wall velocity while, effectively, the tangential velocity will be ignored.


  WallBC_WithSlip2:new{label, group, is_design_surface, num_cntrl_pts}

is Ingo's variant of WallBC_WithSlip for moving mesh simulations for walls
with normal velocity.
It uses ghost cells with appropriate velocity settings.


=== No-slip, fixed-temperature

  WallBC_NoSlip_FixedT:new{Twall, label, group, is_design_surface, num_cntrl_pts}
  or
  WallBC_NoSlip_FixedT0:new{Twall, label, group, is_design_surface, num_cntrl_pts}

is used where we want viscous effects to impose a no-slip velocity
condition and a fixed wall temperature.
The inviscid effect of the solid wall is achieved with the use of ghost cells and
an appropriate reflection of the velocity vector.
We need to set `config.viscous=true` to make the temperature-setting part
of this boundary condition effective.

`Twall`::
  The fixed wall temperature, in degrees K.

`label`::
  _string_, default "" +
  A tag string that may be applied to the boundary.

`group`::
  _string_, default "" +
  A tag or label for the group, to which this boundary belongs.
  It can be used to group the postprocessing of the data for several boundaries together.
  This might be for force and moment estimation, for example.


  WallBC_NoSlip_FixedT1:new{Twall,
     label, group, is_design_surface, num_cntrl_pts}

is variant of the boundary condition that does not use ghost cells and
is suitable for moving-grid simulations.


=== No-slip, adiabatic

  WallBC_NoSlip_Adiabatic:new{label, group, is_design_surface, num_cntrl_pts}
  or
  WallBC_NoSlip_Adiabatic0:new{label, group, is_design_surface, num_cntrl_pts}

is used where we want viscous effects to impose no-slip at the wall
but where there is no heat transfer.
We need to set `config.viscous=true` to make this boundary condition effective.

`label`::
  _string_, default "" +
  A tag string that may be applied to the boundary.

`group`::
  _string_, default "" +
  A tag or label for the group, to which this boundary belongs.
  It can be used to group the postprocessing of the data for several boundaries together.
  This might be for force and moment estimation, for example.


  WallBC_NoSlip_Adiabatic1:new{label, group, is_design_surface, num_cntrl_pts}

is variant of the boundary condition that does not use ghost cells and
is suitable for moving-grid simulations.


=== Translating-surface, fixed-temperature

  WallBC_TranslatingSurface_FixedT:new{Twall, v_trans,
     label, group, is_design_surface, num_cntrl_pts}

Used where we want viscous effects to impose a specified translating velocity condition
and a fixed wall temperature.
By _translating_ we mean that the (flat) wall is moving tangential to the block boundary
and that the grid defining the flow region is not moving.
We need to set `config.viscous=true` to make this boundary condition fully effective.
An example of use is Couette flow between moving plates.

`Twall`::
  The fixed wall temperature, in degrees K.

`v_trans`::
  _Vector3_, default: {x=0.0, y=0.0, z=0.0} +
  Vector velocity of the translating wall.
  The value may be specified as a table of three named (x,y,z) components.

`label`::
  _string_, default "" +
  A tag string that may be applied to the boundary.

`group`::
  _string_, default "" +
  A tag or label for the group, to which this boundary belongs.
  It can be used to group the postprocessing of the data for several boundaries together.
  This might be for force and moment estimation, for example.


=== Translating-surface, adiabatic

  WallBC_TranslatingSurface_Adiabatic:new{v_trans, label, group}


=== Rotating-surface, fixed-temperature

  WallBC_RotatingSurface_FixedT:new{Twall, r_omega, centre, label, group}

=== Rotating-surface, adiabatic

  WallBC_RotatingSurface_Adiabatic:new{r_omega, centre, label, group}


== In-flow

=== Simple supersonic

  InFlowBC_Supersonic:new{flowState, label, group}


=== Static profile

  InFlowBC_StaticProfile:new{fileName, match, label, group}


=== Transient

  InFlowBC_Transient:new{fileName, label, group}


=== Constant flux

  InFlowBC_ConstFlux:new{flowState, label, group}


=== Shock-fitting

  InFlowBC_ShockFitting:new{flowState, label, group}


=== Isentropic from stagnation

  InFlowBC_FromStagnation:new{stagnationState, fileName,
    direction_type, direction_x, direction_y, direction_z,
    alpha, beta, mass_flux, relax_factor, label, group}


== Out-flow


=== Simple flux

  OutFlowBC_SimpleFlux:new{label, group}


=== Simple extrapolation

  OutFlowBC_SimpleExtrapolate:new{xOrder, label, group}


=== Fixed pressure

  OutFlowBC_FixedP:new{p_outside, label, group}


=== Fixed pressure and temperature

  OutFlowBC_FixedPT:new{p_outside, T_outside, label, group}


== Inter-block Exchange

=== Full block-face

  ExchangeBC_FullFace:new{otherBlock, otherFace, orientation,
    reorient_vector_quantities, Rmatrix, label, group}


=== Mapped cell

  ExchangeBC_MappedCell:new{transform_position, c0, n, alpha, delta,
    list_mapped_cells, reorient_vector_quantities, Rmatrix, label, group}


== User Defined
This is a get-out-of-jail boundary condition that allows you to do anything
you wish to code (in Lua).


=== Setting ghost cells

   UserDefinedGhostCellBC:new{fileName, label, group, is_design_surface, num_cntrl_pts}


=== Setting fluxes

  UserDefinedFluxBC:new{fileName, funcName, label, group}


=== Full block-face followed by user-defined

  ExchangeBC_FullFacePlusUDF:new{otherBlock, otherFace, orientation,
    reorient_vector_quantities, Rmatrix, fileName, label, group}


