= Run-time utilities

== Monitoring a simulation

While a calculation runs, its progress can be monitored in a couple of ways.
By default, the simulation program occasionally writes to the console
the time-step count, the current simulation time, the current size of time step,
the current wall-clock time (`WC`), and estimates of the wall-clock time until the
simulation reaches either the final simulation time (`WCtFT`) or the maximum allowed
number of steps (`WCtMS`).
For a simple simulation of a transient flow, this is often sufficent.

=== Viewing residuals

For a simulation that is intended to progress toward a steady solution,
you can monitor the residuals in the flow-field by specifying the `--report-residuals`
command-line option when starting the simulation.
With this option, the residuals for mass, momentum in each of the coordinate directions,
energy, the L2 norm of the collection of residuals and the mass-balance, are written to
the file `config/<job>-residuals.txt`.
This file can be monitored by writing it to another console with `tail -f` or
its content can be rendered graphically with GNUPlot.
See `dgd/examples/eilmer/2D/lat-plate-hakkinen-swbli/sg-lts/` for a sample GNUPlot script
for rendering of this data.
The essential lines from that script are shown here.

  job = "swbli"
  period_seconds = 2.0
  residuals_file = "./config/" . job ."-residuals.txt"
  window_title = "Eilmer4 residuals for ".job
  set term qt title window_title
  set logscale y
  bind "x" "end=1"
  bind "q" "end=1"
  end = 0
  while( end==0 ) {
    set multiplot layout 2,2
    plot residuals_file using "step":"x-mom" with lines, \
      residuals_file using "step":"y-mom" with lines
    plot residuals_file using "step":"energy" with lines
    plot residuals_file using "step":"mass" with lines
    plot residuals_file using "step":"L2" with lines
    pause period_seconds
  }

=== (Lack of) Simulation progress

For large MPI jobs, there is a risk that the part of the calculation will fail
and leave other MPI tasks consuming compute resources while waiting for communication
that will never come.
We provide the `e4monitor` program that can periodically check the progress of a simulation and,
if progress is not being made, terminate the calculation process forcefully.

Progress is indicated by the simulation program writing the current time step number to the
file `config/<job>-progress.txt`.
This file is overwritten each time step.
On completion of a simulation, the word `done` is written to that file.

To use the e4monitor program in your batch scripts,
start it just before using `mpirun` to start your simulation.

  $ e4monitor --job=<jobName> ?--startup=<int>? ?--period=<int>? &

The trailing ampersand indicates that the `e4monitor` program has been started in
the background.
The default values for `startup` and `period` are 30 and 60 seconds respectively.
With these values, the monitor program does not look at the progress file until
30 seconds has elapsed.
It subsequently checks every 60 seconds that the time-step count has increased.
Set these parameters to suit your particular simulation.
If the monitor program does not see progress for a few cycles, it issues a `kill`
command for the mpirun process.
If the simulation finishes successfully, the monitor program will see the word `done`
and will also terminate.
This should give a clean exit for your batch job.


== Compacting a solution

When running a transient-flow simulations with many blocks and
saving the flow data at many time instants, you can end up with thousands of files.
Although not usually a problem on your personal workstation,
storing many small files on a shared supercomputer file system is likely to lead
to trouble with your storage allocation.
To mitigate this problem, there is a utility program to compact and restore job directories.

  $ e4compact --job=<jobName> ?--verbose? ?--force? ?--restore?

This program delegates most of the work to the tar command and
will collect the many solution and grid files into a small set of archive files.
Files that are successfully archived are removed from the directories and,
if the directories are then empty, they are also removed.

Notes::
 * Existing archives will only be updated if the `--force|-f` option is specified.
 * Option `--restore|-r` will extract files from archives and restore the directories.
 * Option `--verbose|-v` will echo the tar commands as they are issued.


