filename=alkandry2014

clean:
	rm -r 	flow\
			grid \
			hist \
			loads \
			plot \
			solid \
			${filename}.control \
			${filename}.list \
			${filename}.times \
			ideal-air-gas-model.lua \
			${filename}.c* \
			${filename}*.svg \
			${filename}*.mpimap
			
	clear
