
-- Conditions file generated by conditions.py on 2025-03-19 16:07:05.337022 using invocation:
-- $ python3 make_conditions/makeconditions.py -a 61 -v 7651 

T_inf = 242.64999999999998      -- K
rho_inf = 0.0002535499832683474  -- kg/m^3
mass_fraction = {N2=0.767, O2=0.233}
u_inf = 7651.0    -- m/s

nBlocks = 16
nib = 4
njb = 4
reltol = 1e-9
masstol= 1e-10

ri = 0.1524
L = 1.295 - ri

