= FlowSolution

In a preparation script, the `FlowSolution` object is used
to initialise the domain with a flow field from another
(completed) job.

 FlowSolution:new{dir=<string>, snapshot=<int|string>, nBlocks=<int>, make_kdtree=<bool>}

`dir` ::
    _string_, no default +
    directory containing completed simulation +
    It is often easy to use relative paths if the simulation is nearby.

`snapshot` ::
    _int_ or _string_, no default +
    read flow field from `snapshot` of completed simulation +
    provide an integer for the snapshot index,
    or to get the last flow field, one can supply the special
    string `"last"` or `"final"`.

`nBlocks` ::
    _int_, no default +
    number of blocks in completed simulation. +
    Note that if you provide a value _smaller_ than the
    total number of blocks in the completed simulation,
    then only blocks up to `nBlocks-1` will be used
    to initialise the flow field. A use case for this would
    if one only want to use some inflow portion of the
    domain when intialising a new simulation.


`make_kdtree` ::
    _bool_, default = false +
    when make_kdtree is selected (=true) the search speed for locating cells
    is considerably improved.
    It does this by using a kd tree filtering and sorting approach.
    There is, however, a startup cost for building the kd tree.

Example of use:

 initial = FlowSolution:new{dir='../inviscid', snapshot='last', nBlocks=4, make_kdtree=true}




