= Running a simulation

The overall process of simulation of a gas flow is divided into
three stages:

  (1) preparation of the defining data,
  (2) running the main simulation program, and
  (3) postprocessing of the output data from the simulation.

Information is passed from one stage to the next in data files.

== Command-line interface

Eilmer tools and commands are invoked at the command line in the form:

`lmr` _verb_ [_options_] [_arguments_]

To get general help:

   $ lmr help

To list all available commands:

   $ lmr help -a

Help is available for a specific command:

   $ lmr help command-name


== Pre-processing
To start a simulation, we need a gas model,
maybe a chemical-kinetics model for reacting flow,
simulation configuration and control files, and
the initial grid and flow state.
Generation of all of these data is the activity of
the pre-processing (or preparation) stage.

=== `prep-gas`
----
include::commands/prep-gas.txt[]
----
=== `prep-reactions`
----
include::commands/prep-reactions.txt[]
----
=== `prep-energy-exchange`
----
include::commands/prep-energy-exchange.txt[]
----
=== `prep-grid`
----
include::commands/prep-grid.txt[]
----
=== `prep-sim`
----
include::commands/prep-sim.txt[]
----

== Run-time
Now that the initial flow and grid files exist, it is time to run the main
flow simulation process.
By default, four executables are built:
`lmr-run`, `lmrZ-run`, `lmr-mpi-run` and `lmrZ-mpi-run`.
The `Z` variants use complex values; the others use real values.
For shared memory, the user can call `lmr run` and the launcher will figure out the best executable to call based on whether one is running `transient` or `steady`.
For running with MPI, things are a bit trickier because we need to play nicely with the MPI launcher.
We recommend using `lmr-mpi-run` for most transient simulations and `lmrZ-mpi-run` for steady mode.

=== `run`
----
include::commands/run.txt[]
----

== Command and control during run-time

There could be several reasons one might like to interrupt the normal flow of a simulation to request an action.
Some examples are: adjust a CFL value; request a current snapshot of the simulation evolution; or stop a simulation early.
The facility to interrupt and act during a simulation is provided by user-edited files.
We have two separate files for `steady` mode and `transient` mode because the kinds of actions available differ
(and due to historical reasons).
In general, these files are re-read at specific step intervals.
If an action is detected at one of the checking intervals, it is executed.

When issuing run-time command and control decisions, there is a trade-off between reproducibility and "getting things done".
In terms of reproducibility, you weaken the record of your simulation settings if you adjust values on-the-fly.
You can mitigate this by keeping good notes in your workbook, and we try to record the actions executed at run-time to STDOUT.
That being said, you might be interested in a one-time simulation and it's handy to be able to adjust how the simulation
proceeds without stopping and restarting.
This can be particularly handy if you have a long-run job (eg. 6--12 hours) on a cluster computer and don't want to re-queue.

=== Issuing run-time commands to steady-state solver (`config.solver_mode = "steady"`)

Users can issue run-time commands to the solver in `steady` mode by editing the file:

`lmrsim/commands-to-steady-mode`

Here is an example file. This particular example does nothing to alter
the run-time behaviour of the simulation since the actions are disabled.
[source,yaml]
----
include::examples/commands-file[]
----

The configuration controlling how often the commands file is read is
part of the Newton-Krylov settings. It is: `steps_between_command_updates`.
The default is 10 steps.
There is a performance cost to the simulation to read and execute commands,
so make an appropriate selection.
If you have a large simulation running on a cluster computer and the cost
per iteration is on the order of minutes, then `steps_between_command_updates = 1` might be useful to you.
That cost of reading the file is small compared to the step update.
On the other hand, for a simulation that runs in seconds and you want to do many as part of a parameter sweep, you might find you do not want the cost of reading the commands file.
In that case, set the `steps_between_command_updates` to a value larger than your maximum steps.

Commands are in the form of *what* and *when*.
There are currently two *what* commands: `write-snapshot` and `stop`.

`write-snapshot` ::
   writes a snapshot in next slot in the snapshot sequence

`stop` ::
   stops the simulation cleanly (but does not necessarily write-on-exit; use in conjuction with `write-snapshot` to achieve a write-on-exit)

In terms of *when*, there are two options:

`at-next-check` ::
    _boolean_, yes|no +
   perform the action next time the commands file is read

`at-next-check-after-step` ::
   _int_, `step number` +
   perform the action at the _next_ check when current step exceeds step number, but don't repeat action until `step number` is changed +
   if set to -1, this is disabled. +
   Example: `steps_between_command_updates` is set to 10 and `at-check-after-step` is set to 15. +
   For these settings, the action is performed at step 20.
   The checks occur at steps: 10, 20, 30, ...
   When check occurs at step 20, then `current step > step number` -> `20 > 15`.
   This is the _next_ check that occurred that satisfied the condition, so the action is performed.

There is a priority order given to the commands. That order is:

1. Writing commands
2. Stop commands

So if you want to write and exit, you can set `at-next-check` to `yes` for
both the write and stop commands.



=== Controlling the time-marching mode at run-time (`config.solver_mode = "transient"`)

See `lmrsim/control` file.

== Post-processing
The Eilmer flow field data is a native format.
We will typically need to process it in some way to make is usable for analysis or visualisation.
Here are some of the Eilmer tools that
can be used as a part of your post-processing.

=== `snapshot2vtk`
----
include::commands/snapshot2vtk.txt[]
----
=== `probe-flow`
----
include::commands/probe-flow.txt[]
----
=== `slice-flow`
----
include::commands/slice-flow.txt[]
----
=== `extract-line`
----
include::commands/extract-line.txt[]
----
=== `compute-norms`
----
include::commands/compute-norms.txt[]
----

