/* accommodation_increments.mac
 * Compute the solution of the system of linear equations symbolically.
 * PJ, 2016-03-20
 *
 * maxima -b accommodation_increments.mac > accommodation_increments.transcript
 */

eq1: v*drho + rho*dv = 0;
eq2: rho*v*dv + dp_gda = -dp_chem;
eq3: v*Etot*drho + (rho*Etot+p)*dv + rho*v*du_gda = -rho*v*du_chem;
eq4: dfdr*drho - dp_gda + dfdu*du_gda = 0;
soln: solve([eq1, eq2, eq3, eq4], [drho, dv, dp_gda, du_gda]);
