-- Auto-generated by prep-gas on: 06-Sep-2021 15:43:19

model = 'IdealGas'
IdealGas = {
   speciesName = 'He',
   mMass = 0.00400260,
   gamma = 1.66666667,
   entropyRefValues = {
      s1 = 0.00000000e+00,
      T1 = 298.15000000,
      p1 = 1.01325000e+05,
   },
   viscosity = {
      model = 'CEA',
      nsegments = 3,
      segment0 = {
         T_lower = 200.0,
         T_upper = 1000.0,
         A =  7.5015944e-01,
         B =  3.5763243e+01,
         C = -2.2121291e+03,
         D =  9.2126352e-01,
      },
      segment1 = {
         T_lower = 1000.0,
         T_upper = 5000.0,
         A =  8.3394166e-01,
         B =  2.2082656e+02,
         C = -5.2852591e+04,
         D =  2.0809361e-01,
      },
      segment2 = {
         T_lower = 5000.0,
         T_upper = 15000.0,
         A =  8.6316349e-01,
         B =  9.6205176e+02,
         C = -1.2498705e+06,
         D = -1.4115714e-01,
      },
   },
   thermCondModel = {
      model = 'CEA',
      nsegments = 3,
      segment0 = {
         T_lower = 200.0,
         T_upper = 1000.0,
         A =  7.5007833e-01,
         B =  3.6577987e+01,
         C = -2.3636600e+03,
         D =  2.9766475e+00,
      },
      segment1 = {
         T_lower = 1000.0,
         T_upper = 5000.0,
         A =  8.3319259e-01,
         B =  2.2157417e+02,
         C = -5.3304530e+04,
         D =  2.2684592e+00,
      },
      segment2 = {
         T_lower = 5000.0,
         T_upper = 15000.0,
         A =  8.5920953e-01,
         B =  8.9873206e+02,
         C = -1.1069262e+06,
         D =  1.9535742e+00,
      },
   }
}
