= State-to-state flow processes
:source-highlighter: rouge


These functions are for computing simple processes involving the general gas models.
In Python, the flow analysis functions are collected as methods of the GasFlow class.
An object of this class needs to be constructed in the context of a particular gas model.

[source,python]
----
# Python
flow = GasFlow(gmodel)
----

In Lua, the functions are already available in the `gas-calc` program in a table called `gasflow`.


== Normal shock

For shock processing when we want to restrict the processing to the ideal-gas behaviour,
use the following function.

[source,python]
----
# Python
v2, vg = flow.ideal_shock(state1, vs, state2)
----

[source,lua]
----
-- Lua
state2, v2, vg = gasflow.ideal_shock(state1, vs)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The initial gas state, before passing through the shock.

`vs`::
  _Float_, no default. +
  Speed of gas, in m/s, coming into the shock (in a shock stationary frame),
  or the speed of the shock into quiescent gas (lab frame).

`state2`::
  _GasState_ object, no default. +
  The state of the gas after shock processing.
  In Python, you need to construct `state2` first,
  then pass it into the function to have its values mutated.

`v2`::
  _Float_ The post-shock gas speed, in m/s, relative to the shock front.

`vg`::
  _Float_ The post-shock gas speed, in m/s, in the lab frame,
  for the case where the shock in moving into a quiescent gas.


For shock processing with more general, but still chemically-frozen, gas behaviour,
use the following function.

[source,python]
----
# Python
v2, vg = flow.normal_shock(state1, vs, state2)
----

[source,lua]
----
-- Lua
state2, v2, vg = gasflow.normal_shock(state1, vs)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The initial gas state, before passing through the shock.

`vs`::
  _Float_, no default. +
  Speed of gas, in m/s, coming into the shock (in a shock stationary frame),
  or the speed of the shock into quiescent gas (lab frame).

`state2`::
  _GasState_ object, no default. +
  The state of the gas after shock processing.
  In Python, you need to construct `state2` first,
  then pass it into the function to have its values mutated.

`v2`::
  _Float_ The post-shock gas speed, in m/s, relative to the shock front.

`vg`::
  _Float_ The post-shock gas speed, in m/s, in the lab frame,
  for the case where the shock in moving into a quiescent gas.


For the case where the pressure ratio is provided, use the function:

[source,python]
----
# Python
vs, v2, vg = flow.normal_shock_p2p1(state1, p2p1, state2)
----

[source,lua]
----
-- Lua
vs, v2, vg = gasflow.normal_shock_p2p1(state1, p2p1)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The initial gas state, before passing through the shock.

`p2p1`::
  _Float_, no default. +
  Ratio of pressures p2/p1 across the shock.

`state2`::
  _GasState_ object, no default for Python but not needed in Lua. +
  The state of the gas after shock processing.

`vs`::
  _Float_ The incident shock speed, in m/s.

`v2`::
  _Float_ The post-shock gas speed, in m/s, relative to the shock front.

`vg`::
  _Float_ The post-shock gas speed, in m/s, in the lab frame,
  for the case where the shock in moving into a quiescent gas.


For a reflected shock, as would be observed in a shock tunnel,
we have the function:

[source,python]
----
# Python
vr = flow.reflected_shock(state2, vg, state5)
----

[source,lua]
----
-- Lua
state5, vr = gasflow.reflected_shock(state2, vg)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The state of the gas approaching the reflected-shock front.

`vg`::
  _Float_ The speed of the incoming gas (in m/s) in the lab frame.

`state5`::
  _GasState_ object, no default in Python. +
  The state of the gas after reflected-shock processing.

The function returns `vr`, the speed of the reflected shock (in m/s) in the lab frame.
In Python, the values within the user-provided `state5` are altered.


== Reversible steady flow

Allow a gas to expand through a steady isentropic process,
from stagnation to a lower pressure.

[source,python]
----
# Python
v = flow.expand_from_stagnation(state0, p_over_p0, state1)
----

[source,lua]
----
-- Lua
state1, v = gasflow.expand_from_stagnation(state0, p_over_p0)
----

Parameters:

`state0`::
  _GasState_ object, no default. +
  The initial stagnation state.

`p_over_p0`::
  _Float_, no default. +
  The pressure of the expanded gas divided by the stagnation pressure.

`state1`::
  _GasState_ object, no default in Python. +
  The state of the gas after expansion.
  In Python, you need to construct `state1` first
  and pass it into the function to have its values mutated.

`v`::
  The velocity (in m/s) of the expanded gas.


Allow a gas to expand through a steady isentropic process,
from stagnation to a particular Mach number.

[source,python]
----
# Python
v = flow.expand_to_mach(state0, mach, state1)
----

[source,lua]
----
-- Lua
state1, v = gasflow.expand_to_mach(state0, mach)
----

Parameters:

`state0`::
  _GasState_ object, no default. +
  The initial stagnation state.

`mach`::
  _Float_, no default. +
  The Mach number of the expanded gas.

`state1`::
  _GasState_ object, no default. +
  The state of the gas after expansion.
  Although you might expect `state1` as output, in Python,
  you need to construct it first
  and pass it into the function to have its values mutated.

The function returns `v`. the velocity (in m/s) of the expanded gas.
The Lua flavour also returns `state1`.


Given a free-stream, compute the corresponding stagnation condition.

[source,python]
----
# Python
flow.total_condition(state1, v1, state0)
----

[source,lua]
----
-- Lua
state0 = gasflow.total_condition(state1, v1)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The free-stream state.

`v1`::
  _Float_, no default. +
  The velocity (in m/s) of the free stream.

`state0`::
  _GasState_ object, no default in Python. +
  The stagnation state, following an isentropic compression from the free-stream state.
  In Python, you need to construct `state0` first
  and pass it into the function to have its values mutated.


== Pitot probe flow

Compute the state of gas at the stagnation point on a Pitot probe.
For a subsonic free-stream flow, this will be the same as for an isentropic compression.
For a supersonic flow, there will be a normal shock, followed by an isentropic compression.

[source,python]
----
# Python
flow.pitot_condition(state1, v1, state2pitot)
----

[source,lua]
----
-- Lua
state2pitot = gasflow.pitot_condition(state1, v1)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The free-stream state.

`v1`::
  _Float_, no default. +
  The velocity (in m/s) of the free stream.

`state2pitot`::
  _GasState_ object, no default. +
  The stagnation state at the probe tip, after compression from the free-stream state.


== Steady flow in a duct

Steady, isentropic flow through a variable-area duct.
Internally, this function iterates guesses for the pressure ratio,
in order to keep mass-flux equal.

[source,python]
----
# Python
v2 = flow.steady_flow_with_area_change(state1, v1, area2_over_area1, state2, tol=1.0e-4)
----

[source,lua]
----
-- Lua
state2, v2 = gasflow.steady_flow_with_area_change(state1, v1, area2_over_area1, tol)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The state at point 1 in the duct.

`v1`::
  _Float_, no default. +
  The velocity (in m/s) at point 1.

`area2_over_area1`::
  _Float_, no default. +
  The ratio of areas of the two points.

`state2`::
  _GasState_ object, no default. +
  The gas state at point 2.

`tol`::
  _Float_, default `1.0e-4` +
  Tolerance on the mass-flux error.


== Unsteady reversible flow

For compression and expansion processes that travel as a wave,
the analysis steps along a characteristic trajectory that traverses the wave
and integrates the effects numerically.

[source,python]
----
# Python
v2 = flow.finite_wave_dp(state1, v1, characteristic, p2, state2, steps=100)
----

[source,lua]
----
-- Lua
state2, v2 = gasflow.finite_wave_dp(state1, v1, characteristic, p2, steps)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The state before wave processing.

`v1`::
  _Float_, no default. +
  The velocity (in m/s) before wave processing.
  Positive velocities are to the right.

`characteristic`::
  _string_, no default. +
  Name of the characteristic trajectory that the integration process follows.
  Options are `"cplus"` and `"cminus"`.
  If the unsteady processing wave is moving left through the gas,
  the integration follows a "cplus" characteristic trajectory
  (from the left initial state to the right final state).

`p2`::
  _Float_, no default. +
  The pressure (in Pa) after wave processing.

`state2`::
  _GasState_ object, no default. +
  The gas state after wave processing.

`steps`::
  _Int_, default: 100 +
  The pressure change is divided into a number of steps and the effects
  are integrated numerically.

`v2`::
  _Float_: +
  the velocity of the gas following wave processing.


For the cases where we know the velocity of the expanded gas,
we can take steps in velocity to get to the expanded state.

[source,python]
----
# Python
v2 = flow.finite_wave_dv(state1, v1, characteristic, v2_target, state2, steps=100, t_min=200.0)
----

[source,lua]
----
-- Lua
state2, v2 = gasflow.finite_wave_dv(state1, v1, characteristic, v2_target, steps, t_min)
----

Input:

`state1`::
  _GasState_ object, no default. +
  The state before wave processing.

`v1`::
  _Float_, no default. +
  The velocity (in m/s) before wave processing.

`characteristic`::
  _string_, no default. +
  Name of the characteristic trajectory that the integration process follows.
  Options are `"cplus"` and `"cminus"`.
  If the unsteady processing wave is moving left through the gas,
  the integration follows a "cplus" characteristic trajectory
  (from the left initial state to the right final state).

`v2_target`::
  _Float_, no default. +
  The expected velocity (in m/s) after wave processing.

`state2`::
  _GasState_ object, no default. +
  The gas state after wave processing.
  Although you might expect `state2` as output, you need to construct it first
  and pass it into the function to have its values mutated.

`steps`::
  _Int_, default: 100 +
  The velocity change is divided into a number of steps and the effects
  are integrated numerically.

`t_min`::
  _Float_, default: 200.0 +
  Minimum temperature (in degrees K) of the gas through the expansion.
  Because we are stepping in velocity, it is easy to demand a final velocity that
  can exceed the maximum velocity for a physically realizable expansion.
  A typical symptom of demanding too strong an expansion is a negative temperature
  for the expanded gas.

`v2`::
  _Float_: the velocity of the gas following wave processing.


== Riemann problem

The Riemann problem is at the core of our larger-scale CFD codes.
Left and Right gas states are allowed to interact at their contact surface.
Processing of each initial state is via a left-running wave (into the Left state) and
a right-running wave (into the Right state).
The results of wave processing are two intermediate states (labelled `star`)
that have a common pressure and velocity at the contact surface.
Osher's approximate Riemann solver assumes that both processing waves are isentropic.

[source,python]
----
# Python
pstar, wstar, wL, wR, velX0 = flow.osher_riemann(stateL, stateR, velL, velR, stateLstar, stateRstar, stateX0)
----

Input:

`stateL`::
  _GasState_ object, no default. +
  The state on the left of the contact surface.

`stateR`::
  _GasState_ object, no default. +
  The state on the right of the contact surface.

`velL`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the left initial state.

`velR`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the right initial state.

`stateLstar`::
  _GasState_ object, no default. +
  The left intermediate state after wave processing.

`stateRstar`::
  _GasState_ object, no default. +
  The right intermediate state after wave processing.

`stateX0`::
  _GasState_ object, no default. +
  The interpolated state at the initial contact-surface location, after wave processing.
  As part of a flow simulation code, the details of this state may be used to compute
  the flux of mass, momentum and energy across the initial constact-surface location.

Although you might expect `stateLstar` and `statRstar` as output,
you need to construct them first and pass them into the function
to have their values mutated.

The function returns:

`pstar`::
  _Float_ The common pressure at the contact surface between the intermediate states.

`wstar`::
  _Float_ The common velocity at the contact surface between the intermediate states.

`wL`::
  _Float_ The leading-edge wave speed of the left-moving wave.
  If the wave is a compression, this is the shock speed.

`wR`::
  _Float_ The leading-edge wave speed of the right-moving wave.
  If the wave is a compression, this is the shock speed.

`velX0`::
  _Float_ The velocity of the gas, interpolated at the initial location of the contact-surface.


== Riemann subproblem for L1d

The Lagrangian flow solver has a specialized Riemann solver at its core.

[source,python]
----
# Python
pstar, wstar = flow.lrivp(stateL, stateR, velL, velR)
----

Input:

`stateL`::
  _GasState_ object, no default. +
  The state on the left of the contact surface.

`stateR`::
  _GasState_ object, no default. +
  The state on the right of the contact surface.

`velL`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the left initial state.

`velR`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the right initial state.

The function returns:

`pstar`::
  _Float_ The common pressure at the contact surface between the intermediate states.

`wstar`::
  _Float_ The common velocity at the contact surface between the intermediate states.


When the gas is up against a solid face of a piston,
we have the contact-surface velocity as known and
we need to compute just the gas pressure at the contact-surface.

[source,python]
----
# Python
pstar = flow.piston_at_left(stateR, velR, wstar)
----

Input:

`stateR`::
  _GasState_ object, no default. +
  The state on the right of the contact surface.

`velR`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the right initial state.

`wstar`::
  _Float_, no default. +
  The velocity (in m/s) of the gas at the contact (piston) surface.

The function returns `pstar` (in Pa), the pressure at the contact surface.


[source,python]
----
# Python
pstar = flow.piston_at_right(stateL, velL, wstar)
----

Input:

`stateL`::
  _GasState_ object, no default. +
  The state on the left of the contact surface.

`velL`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the left initial state.

`wstar`::
  _Float_, no default. +
  The velocity (in m/s) of the gas at the contact (piston) surface.

The function returns `pstar` (in Pa), the pressure at the contact surface.



== Oblique shock

Oblique straight shocks are analysed by splitting the velocity
into normal and tangential components.
The shock angle, with respect to the initial stream direction, is `beta`.
The streamline deflection angle is `theta`.

Given a shock angle, we can get the flow state after shock processing directly.

[source,python]
----
# Python
theta, v2 = flow.theta_oblique(state1, v1, beta, state2)
----

[source,lua]
----
-- Lua
state2, theta, v2 = gasflow.theta_oblique(state1, v1, beta)
----

Parameters:

`state1`::
  _GasState_ object, no default. +
  The state before shock wave processing.

`v1`::
  _Float_, no default. +
  The velocity of the gas (in m/s) before shock wave processing.

`beta`::
  _Float_, no default. +
  Angle, in radians, of the shock with respect to the initial flow direction.

`state2`::
  _GasState_ object, no default. +
  The gas state after wave processing.
  Although you might expect `state2` as output, you need to construct it first
  and pass it into the function to have its values mutated.

`theta`::
  _Float_ the stream deflection angle (in radians)

`v2`::
  _Float_ the speed of the gas in that deflected stream.


When you know the deflection angle and you want the shock angle,
use the following function.

[source,python]
----
# Python
beta = flow.beta_oblique(state1, v1, theta)
----

[source,lua]
----
-- Lua
beta = gasflow.beta_oblique(state1, v1, theta)
----

Input:

`state1`::
  _GasState_ object, no default. +
  The state before shock wave processing.

`v1`::
  _Float_, no default. +
  The velocity of the gas (in m/s) before shock wave processing.

`theta`::
  _Float_, no default. +
  Deflection angle, in radians, of the streamlines through the shock.

The function returns shock angle `beta` for the weak shock solution
for the given streamline deflection angle.
The flow is assumed to remain supersonic following the shock.
The strong-shock solution, resulting in subsonic downstream flow,
would be sensitive the (unspecified) details of whatever is downstream
and supporting the shock.


== Conical shock

For the limits of thermochemically-frozen and thermochemical-equilibrium gases,
there is a conical flow analysis for shock waves.

Given the free-stream condition and a conical shock angle, the radial flow conditions
can be integrated from just after the shock to the supporting conical body.
The axis of the supporting cone is aligned with the free-stream direction.

[source,python]
----
# Python
theta_c, v2_c = flow.theta_cone(state1, v1, beta, state_c)
----

Input:

`state1`::
  _GasState_ object, no default. +
  The free-stream state, before shock wave processing.

`v1`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the free stream, before shock wave processing.

`beta`::
  _Float_, no default. +
  Angle, in radians, of the conical shock with respect to the initial flow direction.

`state_c`::
  _GasState_ object, no default. +
  The gas state at the cone surface.
  Although you might expect `state_c` as output, you need to construct it first
  and pass it into the function to have its values mutated.

The function returns `theta_c` the stream deflection angle (in radians) at the cone surface and
`v2_c`, the speed of the gas in that deflected stream up the conical surface.


When you know the deflecting cone angle and you want the shock angle,
use the following function.

[source,python]
----
# Python
beta = flow.beta_cone(state1, v1, theta)
----

Input:

`state1`::
  _GasState_ object, no default. +
  The free-stream state, before shock wave processing.

`v1`::
  _Float_, no default. +
  The velocity of the gas (in m/s) in the free stream, before shock wave processing.

`theta`::
  _Float_, no default. +
  Angle, in radians, of the deflecting cone.

The function returns shock angle `beta` for the weak shock solution.
The flow is assumed to remain supersonic following the shock.
A subsonic post-shock flow would be associated with a detached shock
and the flow field would not match the assumed conical arrangement.

