= State-to-state processes (ideal gas)

If the calorically-perfect ideal gas model is sufficient for your analysis needs,
there is simple set of ideal-gas relations collected into the `eilmer.ideal_gas`
package.

The following functions do not use the generalized gas models but assume a gas bahaviour
for fixed ratio of specific heats.

To get access to the functions, import the module into your Python script.
For example:

----
import eilmer.ideal_gas_flow as igf
M = 2.0
print("Normal shock jump...")
print("Computed: M=%g: M2=%g, T2/T1=%g, p2/p1=%g, r2/r1=%g" %
      (M, igf.m2_shock(M), igf.T2_T1(M), igf.p2_p1(M), igf.r2_r1(M)))
print("Expected: M1=2, M2=0.5774, T2/T1=1.687, p2/p1=4.50, r2/r1=2.667")
----


== Isentropic/adiabatic steady flow

  igf.A_Astar(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number at area `A`, assuming sonic condition at area `Astar`

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns area ratio, `A/Astar`, for an isentropic, quasi-one-dimensional flow.


  igf.T0_T(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `T0/T`, the ratio of total temperature over static temperature for adiabatic flow.


  igf.p0_p(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `p0/p`, the ratio of total pressure over static pressure for isentropic flow.

  igf.r0_r(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `rho0/rho`, the ratio of stagnation density over local for isentropic flow.


== Normal shock

  igf.m2_shock(M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `m2`, Mach number following the shock processing.


  igf.r2_r1(M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns density ratio, `r2/r1`, across a normal shock.


  igf.v2_v1(M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns velocity ratio, `v2/v1`, across a normal shock.


  igf.p2_p1(M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns static pressure ratio, `p2/p1`, across a normal shock.


  igf.T2_T1(M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns static temperature ratio, `T2/T1`, across a normal shock.


  igf.p02_p01(M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns stagnation pressure ratio, `p02/p01`, across a normal shock.


  igf.ds_Cv(M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns nondimensional entropy change, `ds/Cv`, across a normal shock.


  igf.pitot_p(p1, M1, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns pitot pressure for a specified Mach number free-stream flow.
The value will have the same units as input `p1`.



== Flow with heat addition.

One-dimensional flow with heat addition is also known as
Rayleigh-line flow.
The flow starts with local Mach number, `M`, and (hypothetically) enough heat
is added for the flow to reach sonic (`Mstar=1`) condition.

  igf.T0_T0star(M, g=1.4)

Input:

`M`::
  _Float_, no default. initial Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `T0/T0star` where `T0` is the total temperature of the initial flow
and `T0star` is the total temperature that would be achieved if enough heat
is added to get to the sonic condition.


  igf.M_Rayleigh(T0T0star, g=1.4)

Input:

`T0T0star`::
  _Float_, no default. T0/T0star where T0 is the total temperature of
  the initial flow and T0star is the total temperature that would be
  achieved if enough heat is added to get to the sonic condition.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns the initial Mach number, `M`, of the flow.


  igf.T_Tstar(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `T/Tstar` where `T` is the static temperature of the initial flow
and `Tstar` is the static temperature that would be achieved if enough heat
is added to get to sonic condition.


  igf.p_pstar(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `p/pstar` where `p` is the static pressure of the initial flow
and `pstar` is the static pressure that would be achieved if enough heat
is added to get to sonic conditions.


  igf.r_rstar(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns density ratio, `rho/rhostar`, where `rho` is the density
of the initial flow and `rhostar` is the density that would be achieved
if enough heat is added to get to sonic conditions.


  igf.p0_p0star(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `p0/p0star` where `p0` is the total pressure of the initial flow
and `p0star` is the total pressure that would be achieved
if enough heat is added to get to sonic conditions.

== Supersonic turning

  igf.PM1(M, g=1.4)

Input:

`M`::
  _Float_, no default. Mach number.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns Prandtl-Meyer function value, in radians.


  igf.PM2(nu, g=1.4)

Input:

`nu`::
  _Float_, no default. Prandtl-Meyer function value, in radians.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns corresponding Mach number.


== Oblique shock

  igf.beta_obl(M1, theta, g=1.4, tol=1.0e-6)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`theta`::
  _Float_, no default. Steamline deflection angle, in radians.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns shock angle, `beta` (in radians), with respect to the
original stream direction.


  igf.beta_obl2(M1, p2_p1, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`p2_p1`::
  _Float_, no default. +
  Static pressure ratio, `p2/p1`, across the shock.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns shock angle, `beta` (in radians), with respect to the
original stream direction.

  igf.theta_obl(M1, beta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns deflection angle of the stream, `theta` (in radians).


  igf.M2_obl(M1, beta, theta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`theta`::
  _Float_, no default. Steamline deflection angle, in radians.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `M2`, Mach number in flow after the shock.


  igf.r2_r1_obl(M1, beta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns density ratio, `rho2/rho1` across an oblique shock.


  igf.vn2_vn1_obl(M1, beta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns normal-velocity ratio, `vn1/vn2`, across an oblique shock.


  igf.v2_v1_obl(M1, beta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns flow-speed ratio, `v2/v1`, across an oblique shock.


  igf.p2_p1_obl(M1, beta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns static pressure ratio, `p2/p1`, across an oblique shock.


  igf.T2_T1_obl(M1, beta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns static temperature ratio, `T2/T1`, across an oblique shock.


  igf.p02_p01_obl(M1, beta, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas before the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns ratio of stagnation pressures, `p02/p01`, across an oblique shock.



== Taylor-Maccoll cone flow

Compute the cone-surface angle and conditions given the shock wave angle.
The computation starts with the oblique-shock jump and then integrates
across theta until V_theta goes through zero.
The cone surface corresponds to `V_theta == 0`.

  igf.theta_cone(V1, p1, T1, beta, R=287.1, g=1.4)

Input:

`V1`::
  _Float_, no default. Speed of gas (in m/s) entering the shock.

`p1`::
  _Float_, no default. Static pressure of gas (in Pa) entering the shock.

`T1`::
  _Float_, no default. Static temperature of gas (in K) entering the shock.

`beta`::
  _Float_, no default. +
  Shock angle, in radians, relative to the original stream direction.

`R`::
  _Float_, default: 287.1 +
  Gas constant, in `J/kg.K`

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns tuple of (theta_c, V_c, p_c, T_c).

`theta_c`::
  stream deflection angle, in radians

`V_c`::
  the cone-surface speed of gas, in m/s

`p_c`::
  the cone-surface pressure, in Pa

`T_c`::
  the cone-surface static temperature, in K


  igf.beta_cone(V1, p1, T1, theta, R=287.1, g=1.4)

Input:

`V1`::
  _Float_, no default. Speed of gas (in m/s) entering the shock.

`p1`::
  _Float_, no default. Static pressure of gas (in Pa) entering the shock.

`T1`::
  _Float_, no default. Static temperature of gas (in K) entering the shock.

`theta`::
  _Float_, no default. +
  Cone deflection angle, in radians.

`R`::
  _Float_, default: 287.1 +
  Gas constant, in `J/kg.K`

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `beta`, the shock wave angle (in radians) with respect to the free-stream flow direction.


  igf.beta_cone2(M1, theta, R=287.1, g=1.4)

Input:

`M1`::
  _Float_, no default. Mach number of gas entering the shock.

`theta`::
  _Float_, no default. +
  Cone deflection angle, in radians.

`R`::
  _Float_, default: 287.1 +
  Gas constant, in `J/kg.K`

`g`::
  _Float_, default: 1.4 +
  Ratio of specific heats

Returns `beta`, the shock wave angle (in radians) with respect to the free-stream flow direction.

